// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR Resource: AdverseEvent

import * as fhir from '../fhir.js';

import { AdverseEventCausalityAssessValueSet, AdverseEventCausalityAssessValueSetType,} from '../fhirValueSets/AdverseEventCausalityAssessValueSet.js';
import { AdverseEventCausalityAssessValueSetEnum } from '../valueSetEnums.js';
import { AdverseEventCausalityMethodValueSet, AdverseEventCausalityMethodValueSetType,} from '../fhirValueSets/AdverseEventCausalityMethodValueSet.js';
import { AdverseEventCausalityMethodValueSetEnum } from '../valueSetEnums.js';
import { AdverseEventActualityValueSet, AdverseEventActualityValueSetType,} from '../fhirValueSets/AdverseEventActualityValueSet.js';
import { AdverseEventActualityValueSetEnum } from '../valueSetEnums.js';
import { AdverseEventCategoryValueSet, AdverseEventCategoryValueSetType,} from '../fhirValueSets/AdverseEventCategoryValueSet.js';
import { AdverseEventCategoryValueSetEnum } from '../valueSetEnums.js';
import { AdverseEventTypeValueSet, AdverseEventTypeValueSetType,} from '../fhirValueSets/AdverseEventTypeValueSet.js';
import { AdverseEventTypeValueSetEnum } from '../valueSetEnums.js';
import { AdverseEventSeriousnessValueSet, AdverseEventSeriousnessValueSetType,} from '../fhirValueSets/AdverseEventSeriousnessValueSet.js';
import { AdverseEventSeriousnessValueSetEnum } from '../valueSetEnums.js';
import { AdverseEventSeverityValueSet, AdverseEventSeverityValueSetType,} from '../fhirValueSets/AdverseEventSeverityValueSet.js';
import { AdverseEventSeverityValueSetEnum } from '../valueSetEnums.js';
import { AdverseEventOutcomeValueSet, AdverseEventOutcomeValueSetType,} from '../fhirValueSets/AdverseEventOutcomeValueSet.js';
import { AdverseEventOutcomeValueSetEnum } from '../valueSetEnums.js';
import { IssueTypeValueSetEnum } from '../valueSetEnums.js';
import { IssueSeverityValueSetEnum } from '../valueSetEnums.js';
/**
 * Valid arguments for the AdverseEventSuspectEntityCausality type.
 */
export interface AdverseEventSuspectEntityCausalityArgs extends fhir.BackboneElementArgs {
  /**
   * Assessment of if the entity caused the event.
   */
  assessment?: fhir.CodeableConceptArgs|undefined;
  /**
   * AdverseEvent.suspectEntity.causalityProductRelatedness.
   */
  productRelatedness?: fhir.FhirString|string|undefined;
  /**
   * AdverseEvent.suspectEntity.causalityAuthor.
   */
  author?: fhir.ReferenceArgs|undefined;
  /**
   * ProbabilityScale | Bayesian | Checklist.
   */
  method?: fhir.CodeableConceptArgs|undefined;
}

/**
 * Information on the possible cause of the event.
 */
export class AdverseEventSuspectEntityCausality extends fhir.BackboneElement {
  readonly __dataType:string = 'AdverseEventSuspectEntityCausality';
  /**
   * Assessment of if the entity caused the event.
   */
  public assessment?: fhir.CodeableConcept|undefined;
  /**
   * AdverseEvent.suspectEntity.causalityProductRelatedness.
   */
  public productRelatedness?: fhir.FhirString|undefined;
  /**
   * AdverseEvent.suspectEntity.causalityAuthor.
   */
  public author?: fhir.Reference|undefined;
  /**
   * ProbabilityScale | Bayesian | Checklist.
   */
  public method?: fhir.CodeableConcept|undefined;
  /**
   * Default constructor for AdverseEventSuspectEntityCausality - initializes any required elements to null if a value is not provided.
   */
  constructor(source:Partial<AdverseEventSuspectEntityCausalityArgs> = {}, options:fhir.FhirConstructorOptions = {}) {
    super(source, options);
    if (source['assessment']) { this.assessment = new fhir.CodeableConcept(source.assessment); }
    if (source['productRelatedness']) { this.productRelatedness = new fhir.FhirString({value: source.productRelatedness}); }
    if (source['author']) { this.author = new fhir.Reference(source.author); }
    if (source['method']) { this.method = new fhir.CodeableConcept(source.method); }
  }
  /**
   * Example-bound Value Set for assessment
   */
  public static assessmentExampleValueSet():AdverseEventCausalityAssessValueSetType {
    return AdverseEventCausalityAssessValueSet;
  }
  /**
   * Example-bound Value Set for method
   */
  public static methodExampleValueSet():AdverseEventCausalityMethodValueSetType {
    return AdverseEventCausalityMethodValueSet;
  }
  /**
   * Function to perform basic model validation (e.g., check if required elements are present).
   */
  public override doModelValidation():fhir.OperationOutcome {
    var outcome:fhir.OperationOutcome = super.doModelValidation();
    if (this["assessment"]) { outcome.issue!.push(...this.assessment.doModelValidation().issue!); }
    if (this["productRelatedness"]) { outcome.issue!.push(...this.productRelatedness.doModelValidation().issue!); }
    if (this["author"]) { outcome.issue!.push(...this.author.doModelValidation().issue!); }
    if (this["method"]) { outcome.issue!.push(...this.method.doModelValidation().issue!); }
    return outcome;
  }
  /**
   * Function to strip invalid element values for serialization.
   */
  public toJSON() {
    return fhir.fhirToJson(this);
  }
}
/**
 * Valid arguments for the AdverseEventSuspectEntity type.
 */
export interface AdverseEventSuspectEntityArgs extends fhir.BackboneElementArgs {
  /**
   * Identifies the actual instance of what caused the adverse event.  May be a substance, medication, medication administration, medication statement or a device.
   */
  instance: fhir.ReferenceArgs|null;
  /**
   * Information on the possible cause of the event.
   */
  causality?: fhir.AdverseEventSuspectEntityCausalityArgs[]|undefined;
}

/**
 * Describes the entity that is suspected to have caused the adverse event.
 */
export class AdverseEventSuspectEntity extends fhir.BackboneElement {
  readonly __dataType:string = 'AdverseEventSuspectEntity';
  /**
   * Identifies the actual instance of what caused the adverse event.  May be a substance, medication, medication administration, medication statement or a device.
   */
  public instance: fhir.Reference|null;
  /**
   * Information on the possible cause of the event.
   */
  public causality?: fhir.AdverseEventSuspectEntityCausality[]|undefined = [];
  /**
   * Default constructor for AdverseEventSuspectEntity - initializes any required elements to null if a value is not provided.
   */
  constructor(source:Partial<AdverseEventSuspectEntityArgs> = {}, options:fhir.FhirConstructorOptions = {}) {
    super(source, options);
    if (source['instance']) { this.instance = new fhir.Reference(source.instance); }
    else { this.instance = null; }
    if (source['causality']) { this.causality = source.causality.map((x) => new fhir.AdverseEventSuspectEntityCausality(x)); }
  }
  /**
   * Function to perform basic model validation (e.g., check if required elements are present).
   */
  public override doModelValidation():fhir.OperationOutcome {
    var outcome:fhir.OperationOutcome = super.doModelValidation();
    if (!this['instance']) {
      outcome.issue!.push(new fhir.OperationOutcomeIssue({ severity: IssueSeverityValueSetEnum.Error, code: IssueTypeValueSetEnum.RequiredElementMissing,  diagnostics: "Missing required property instance:fhir.Reference fhir: AdverseEvent.suspectEntity.instance:Reference", }));
    }
    if (this["instance"]) { outcome.issue!.push(...this.instance.doModelValidation().issue!); }
    if (this["causality"]) { this.causality.forEach((x) => { outcome.issue!.push(...x.doModelValidation().issue!); }) }
    return outcome;
  }
  /**
   * Function to strip invalid element values for serialization.
   */
  public toJSON() {
    return fhir.fhirToJson(this);
  }
}
/**
 * Valid arguments for the AdverseEvent type.
 */
export interface AdverseEventArgs extends fhir.DomainResourceArgs {
  /**
   * Resource Type Name
   */
  resourceType: "AdverseEvent"|undefined;
  /**
   * This is a business identifier, not a resource identifier (see [discussion](resource.html#identifiers)).  It is best practice for the identifier to only appear on a single resource instance, however business practices may occasionally dictate that multiple resource instances with the same identifier can exist - possibly even with different resource types.  For example, multiple Patient and a Person resource instance might share the same social insurance number.
   */
  identifier?: fhir.IdentifierArgs|undefined;
  /**
   * Whether the event actually happened, or just had the potential to. Note that this is independent of whether anyone was affected or harmed or how severely.
   */
  actuality: AdverseEventActualityValueSetEnum|null;
  /**
   * The overall type of event, intended for search and filtering purposes.
   */
  category?: fhir.CodeableConceptArgs[]|undefined;
  /**
   * This element defines the specific type of event that occurred or that was prevented from occurring.
   */
  event?: fhir.CodeableConceptArgs|undefined;
  /**
   * If AdverseEvent.resultingCondition differs among members of the group, then use Patient as the subject.
   */
  subject: fhir.ReferenceArgs|null;
  /**
   * This will typically be the encounter the event occurred within, but some activities may be initiated prior to or after the official completion of an encounter but still be tied to the context of the encounter.  For example, if a medication administration was considered an adverse event because it resulted in a rash, then the encounter when the medication administration was given is the context.  If the patient reports the AdverseEvent during a second encounter, that second encounter is not the context.
   */
  encounter?: fhir.ReferenceArgs|undefined;
  /**
   * The date (and perhaps time) when the adverse event occurred.
   */
  date?: fhir.FhirDateTime|string|undefined;
  /**
   * Estimated or actual date the AdverseEvent began, in the opinion of the reporter.
   */
  detected?: fhir.FhirDateTime|string|undefined;
  /**
   * The recordedDate represents the date when this particular AdverseEvent record was created in the system, not the date of the most recent update.  The date of the last record modification can be retrieved from the resource metadata.
   */
  recordedDate?: fhir.FhirDateTime|string|undefined;
  /**
   * Includes information about the reaction that occurred as a result of exposure to a substance (for example, a drug or a chemical).
   */
  resultingCondition?: fhir.ReferenceArgs[]|undefined;
  /**
   * The information about where the adverse event occurred.
   */
  location?: fhir.ReferenceArgs|undefined;
  /**
   * Assessment whether this event was of real importance.
   */
  seriousness?: fhir.CodeableConceptArgs|undefined;
  /**
   * Describes the severity of the adverse event, in relation to the subject. Contrast to AdverseEvent.seriousness - a severe rash might not be serious, but a mild heart problem is.
   */
  severity?: fhir.CodeableConceptArgs|undefined;
  /**
   * Describes the type of outcome from the adverse event.
   */
  outcome?: fhir.CodeableConceptArgs|undefined;
  /**
   * Information on who recorded the adverse event.  May be the patient or a practitioner.
   */
  recorder?: fhir.ReferenceArgs|undefined;
  /**
   * Parties that may or should contribute or have contributed information to the adverse event, which can consist of one or more activities.  Such information includes information leading to the decision to perform the activity and how to perform the activity (e.g. consultant), information that the activity itself seeks to reveal (e.g. informant of clinical history), or information about what activity was performed (e.g. informant witness).
   */
  contributor?: fhir.ReferenceArgs[]|undefined;
  /**
   * Describes the entity that is suspected to have caused the adverse event.
   */
  suspectEntity?: fhir.AdverseEventSuspectEntityArgs[]|undefined;
  /**
   * AdverseEvent.subjectMedicalHistory.
   */
  subjectMedicalHistory?: fhir.ReferenceArgs[]|undefined;
  /**
   * AdverseEvent.referenceDocument.
   */
  referenceDocument?: fhir.ReferenceArgs[]|undefined;
  /**
   * AdverseEvent.study.
   */
  study?: fhir.ReferenceArgs[]|undefined;
}

/**
 * Actual or  potential/avoided event causing unintended physical injury resulting from or contributed to by medical care, a research study or other healthcare setting factors that requires additional monitoring, treatment, or hospitalization, or that results in death.
 */
export class AdverseEvent extends fhir.DomainResource {
  readonly __dataType:string = 'AdverseEvent';
  /**
   * Resource Type Name
   */
  public resourceType: "AdverseEvent";
  /**
   * This is a business identifier, not a resource identifier (see [discussion](resource.html#identifiers)).  It is best practice for the identifier to only appear on a single resource instance, however business practices may occasionally dictate that multiple resource instances with the same identifier can exist - possibly even with different resource types.  For example, multiple Patient and a Person resource instance might share the same social insurance number.
   */
  public identifier?: fhir.Identifier|undefined;
  /**
   * Whether the event actually happened, or just had the potential to. Note that this is independent of whether anyone was affected or harmed or how severely.
   */
  public actuality: AdverseEventActualityValueSetEnum|null;
  /**
   * The overall type of event, intended for search and filtering purposes.
   */
  public category?: fhir.CodeableConcept[]|undefined = [];
  /**
   * This element defines the specific type of event that occurred or that was prevented from occurring.
   */
  public event?: fhir.CodeableConcept|undefined;
  /**
   * If AdverseEvent.resultingCondition differs among members of the group, then use Patient as the subject.
   */
  public subject: fhir.Reference|null;
  /**
   * This will typically be the encounter the event occurred within, but some activities may be initiated prior to or after the official completion of an encounter but still be tied to the context of the encounter.  For example, if a medication administration was considered an adverse event because it resulted in a rash, then the encounter when the medication administration was given is the context.  If the patient reports the AdverseEvent during a second encounter, that second encounter is not the context.
   */
  public encounter?: fhir.Reference|undefined;
  /**
   * The date (and perhaps time) when the adverse event occurred.
   */
  public date?: fhir.FhirDateTime|undefined;
  /**
   * Estimated or actual date the AdverseEvent began, in the opinion of the reporter.
   */
  public detected?: fhir.FhirDateTime|undefined;
  /**
   * The recordedDate represents the date when this particular AdverseEvent record was created in the system, not the date of the most recent update.  The date of the last record modification can be retrieved from the resource metadata.
   */
  public recordedDate?: fhir.FhirDateTime|undefined;
  /**
   * Includes information about the reaction that occurred as a result of exposure to a substance (for example, a drug or a chemical).
   */
  public resultingCondition?: fhir.Reference[]|undefined = [];
  /**
   * The information about where the adverse event occurred.
   */
  public location?: fhir.Reference|undefined;
  /**
   * Assessment whether this event was of real importance.
   */
  public seriousness?: fhir.CodeableConcept|undefined;
  /**
   * Describes the severity of the adverse event, in relation to the subject. Contrast to AdverseEvent.seriousness - a severe rash might not be serious, but a mild heart problem is.
   */
  public severity?: fhir.CodeableConcept|undefined;
  /**
   * Describes the type of outcome from the adverse event.
   */
  public outcome?: fhir.CodeableConcept|undefined;
  /**
   * Information on who recorded the adverse event.  May be the patient or a practitioner.
   */
  public recorder?: fhir.Reference|undefined;
  /**
   * Parties that may or should contribute or have contributed information to the adverse event, which can consist of one or more activities.  Such information includes information leading to the decision to perform the activity and how to perform the activity (e.g. consultant), information that the activity itself seeks to reveal (e.g. informant of clinical history), or information about what activity was performed (e.g. informant witness).
   */
  public contributor?: fhir.Reference[]|undefined = [];
  /**
   * Describes the entity that is suspected to have caused the adverse event.
   */
  public suspectEntity?: fhir.AdverseEventSuspectEntity[]|undefined = [];
  /**
   * AdverseEvent.subjectMedicalHistory.
   */
  public subjectMedicalHistory?: fhir.Reference[]|undefined = [];
  /**
   * AdverseEvent.referenceDocument.
   */
  public referenceDocument?: fhir.Reference[]|undefined = [];
  /**
   * AdverseEvent.study.
   */
  public study?: fhir.Reference[]|undefined = [];
  /**
   * Default constructor for AdverseEvent - initializes any required elements to null if a value is not provided.
   */
  constructor(source:Partial<AdverseEventArgs> = {}, options:fhir.FhirConstructorOptions = {}) {
    super(source, options);
    this.resourceType = 'AdverseEvent';
    if (source['identifier']) { this.identifier = new fhir.Identifier(source.identifier); }
    if (source['actuality']) { this.actuality = source.actuality; }
    else { this.actuality = null; }
    if (source['category']) { this.category = source.category.map((x) => new fhir.CodeableConcept(x)); }
    if (source['event']) { this.event = new fhir.CodeableConcept(source.event); }
    if (source['subject']) { this.subject = new fhir.Reference(source.subject); }
    else { this.subject = null; }
    if (source['encounter']) { this.encounter = new fhir.Reference(source.encounter); }
    if (source['date']) { this.date = new fhir.FhirDateTime({value: source.date}); }
    if (source['detected']) { this.detected = new fhir.FhirDateTime({value: source.detected}); }
    if (source['recordedDate']) { this.recordedDate = new fhir.FhirDateTime({value: source.recordedDate}); }
    if (source['resultingCondition']) { this.resultingCondition = source.resultingCondition.map((x) => new fhir.Reference(x)); }
    if (source['location']) { this.location = new fhir.Reference(source.location); }
    if (source['seriousness']) { this.seriousness = new fhir.CodeableConcept(source.seriousness); }
    if (source['severity']) { this.severity = new fhir.CodeableConcept(source.severity); }
    if (source['outcome']) { this.outcome = new fhir.CodeableConcept(source.outcome); }
    if (source['recorder']) { this.recorder = new fhir.Reference(source.recorder); }
    if (source['contributor']) { this.contributor = source.contributor.map((x) => new fhir.Reference(x)); }
    if (source['suspectEntity']) { this.suspectEntity = source.suspectEntity.map((x) => new fhir.AdverseEventSuspectEntity(x)); }
    if (source['subjectMedicalHistory']) { this.subjectMedicalHistory = source.subjectMedicalHistory.map((x) => new fhir.Reference(x)); }
    if (source['referenceDocument']) { this.referenceDocument = source.referenceDocument.map((x) => new fhir.Reference(x)); }
    if (source['study']) { this.study = source.study.map((x) => new fhir.Reference(x)); }
  }
  /**
   * Required-bound Value Set for actuality
   */
  public static actualityRequiredValueSet():AdverseEventActualityValueSetType {
    return AdverseEventActualityValueSet;
  }
  /**
   * Extensible-bound Value Set for category
   */
  public static categoryExtensibleValueSet():AdverseEventCategoryValueSetType {
    return AdverseEventCategoryValueSet;
  }
  /**
   * Example-bound Value Set for event
   */
  public static eventExampleValueSet():AdverseEventTypeValueSetType {
    return AdverseEventTypeValueSet;
  }
  /**
   * Example-bound Value Set for seriousness
   */
  public static seriousnessExampleValueSet():AdverseEventSeriousnessValueSetType {
    return AdverseEventSeriousnessValueSet;
  }
  /**
   * Required-bound Value Set for severity
   */
  public static severityRequiredValueSet():AdverseEventSeverityValueSetType {
    return AdverseEventSeverityValueSet;
  }
  /**
   * Required-bound Value Set for outcome
   */
  public static outcomeRequiredValueSet():AdverseEventOutcomeValueSetType {
    return AdverseEventOutcomeValueSet;
  }
  /**
   * Function to perform basic model validation (e.g., check if required elements are present).
   */
  public override doModelValidation():fhir.OperationOutcome {
    var outcome:fhir.OperationOutcome = super.doModelValidation();
    if (!this['resourceType']) {
      outcome.issue!.push(new fhir.OperationOutcomeIssue({ severity: IssueSeverityValueSetEnum.Error, code: IssueTypeValueSetEnum.RequiredElementMissing,  diagnostics: "Missing required property resourceType:'AdverseEvent' fhir: AdverseEvent.resourceType:'AdverseEvent'", }));
    }
    if (this["identifier"]) { outcome.issue!.push(...this.identifier.doModelValidation().issue!); }
    if (!this['actuality']) {
      outcome.issue!.push(new fhir.OperationOutcomeIssue({ severity: IssueSeverityValueSetEnum.Error, code: IssueTypeValueSetEnum.RequiredElementMissing,  diagnostics: "Missing required property actuality:AdverseEventActualityValueSetEnum fhir: AdverseEvent.actuality:code", }));
    }
    if (this["category"]) { this.category.forEach((x) => { outcome.issue!.push(...x.doModelValidation().issue!); }) }
    if (this["event"]) { outcome.issue!.push(...this.event.doModelValidation().issue!); }
    if (!this['subject']) {
      outcome.issue!.push(new fhir.OperationOutcomeIssue({ severity: IssueSeverityValueSetEnum.Error, code: IssueTypeValueSetEnum.RequiredElementMissing,  diagnostics: "Missing required property subject:fhir.Reference fhir: AdverseEvent.subject:Reference", }));
    }
    if (this["subject"]) { outcome.issue!.push(...this.subject.doModelValidation().issue!); }
    if (this["encounter"]) { outcome.issue!.push(...this.encounter.doModelValidation().issue!); }
    if (this["date"]) { outcome.issue!.push(...this.date.doModelValidation().issue!); }
    if (this["detected"]) { outcome.issue!.push(...this.detected.doModelValidation().issue!); }
    if (this["recordedDate"]) { outcome.issue!.push(...this.recordedDate.doModelValidation().issue!); }
    if (this["resultingCondition"]) { this.resultingCondition.forEach((x) => { outcome.issue!.push(...x.doModelValidation().issue!); }) }
    if (this["location"]) { outcome.issue!.push(...this.location.doModelValidation().issue!); }
    if (this["seriousness"]) { outcome.issue!.push(...this.seriousness.doModelValidation().issue!); }
    if (this["severity"]) { outcome.issue!.push(...this.severity.doModelValidation().issue!); }
    if (this["outcome"]) { outcome.issue!.push(...this.outcome.doModelValidation().issue!); }
    if (this["recorder"]) { outcome.issue!.push(...this.recorder.doModelValidation().issue!); }
    if (this["contributor"]) { this.contributor.forEach((x) => { outcome.issue!.push(...x.doModelValidation().issue!); }) }
    if (this["suspectEntity"]) { this.suspectEntity.forEach((x) => { outcome.issue!.push(...x.doModelValidation().issue!); }) }
    if (this["subjectMedicalHistory"]) { this.subjectMedicalHistory.forEach((x) => { outcome.issue!.push(...x.doModelValidation().issue!); }) }
    if (this["referenceDocument"]) { this.referenceDocument.forEach((x) => { outcome.issue!.push(...x.doModelValidation().issue!); }) }
    if (this["study"]) { this.study.forEach((x) => { outcome.issue!.push(...x.doModelValidation().issue!); }) }
    return outcome;
  }
  /**
   * Function to strip invalid element values for serialization.
   */
  public toJSON() {
    return fhir.fhirToJson(this);
  }
}
