// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
  // Primitive Naming Style: None
  // Complex Type / Resource Naming Style: PascalCase
  // Interaction Naming Style: None
  // Extension Support: NonPrimitive
// Minimum TypeScript Version: 3.7
import * as fhir from '../fhir'
/**
 * The marketing status describes the date when a medicinal product is actually put on the market or the date as of which it is no longer available.
 */
export type IMarketingStatus = fhir.IBackboneElement & {
  /**
   * The country in which the marketing authorisation has been granted shall be specified It should be specified using the ISO 3166 ‑ 1 alpha-2 code elements.
   */
  country: fhir.ICodeableConcept|null;
  /**
   * The date when the Medicinal Product is placed on the market by the Marketing Authorisation Holder (or where applicable, the manufacturer/distributor) in a country and/or jurisdiction shall be provided A complete date consisting of day, month and year shall be specified using the ISO 8601 date format NOTE “Placed on the market” refers to the release of the Medicinal Product into the distribution chain.
   */
  dateRange: fhir.IPeriod|null;
  /**
   * Where a Medicines Regulatory Agency has granted a marketing authorisation for which specific provisions within a jurisdiction apply, the jurisdiction can be specified using an appropriate controlled terminology The controlled term and the controlled term identifier shall be specified.
   */
  jurisdiction?: fhir.ICodeableConcept|undefined;
  /**
   * The date when the Medicinal Product is placed on the market by the Marketing Authorisation Holder (or where applicable, the manufacturer/distributor) in a country and/or jurisdiction shall be provided A complete date consisting of day, month and year shall be specified using the ISO 8601 date format NOTE “Placed on the market” refers to the release of the Medicinal Product into the distribution chain.
   */
  restoreDate?: string|undefined;
  _restoreDate?: fhir.IFhirElement|undefined;
  /**
   * This attribute provides information on the status of the marketing of the medicinal product See ISO/TS 20443 for more information and examples.
   */
  status: fhir.ICodeableConcept|null;
}
/**
 * The marketing status describes the date when a medicinal product is actually put on the market or the date as of which it is no longer available.
 */
export class MarketingStatus extends fhir.BackboneElement implements fhir.IMarketingStatus {
  /**
   * The country in which the marketing authorisation has been granted shall be specified It should be specified using the ISO 3166 ‑ 1 alpha-2 code elements.
   */
  public country: fhir.CodeableConcept|null;
  /**
   * The date when the Medicinal Product is placed on the market by the Marketing Authorisation Holder (or where applicable, the manufacturer/distributor) in a country and/or jurisdiction shall be provided A complete date consisting of day, month and year shall be specified using the ISO 8601 date format NOTE “Placed on the market” refers to the release of the Medicinal Product into the distribution chain.
   */
  public dateRange: fhir.Period|null;
  /**
   * Where a Medicines Regulatory Agency has granted a marketing authorisation for which specific provisions within a jurisdiction apply, the jurisdiction can be specified using an appropriate controlled terminology The controlled term and the controlled term identifier shall be specified.
   */
  public jurisdiction?: fhir.CodeableConcept|undefined;
  /**
   * The date when the Medicinal Product is placed on the market by the Marketing Authorisation Holder (or where applicable, the manufacturer/distributor) in a country and/or jurisdiction shall be provided A complete date consisting of day, month and year shall be specified using the ISO 8601 date format NOTE “Placed on the market” refers to the release of the Medicinal Product into the distribution chain.
   */
  public restoreDate?: string|undefined;
  public _restoreDate?: fhir.FhirElement|undefined;
  /**
   * This attribute provides information on the status of the marketing of the medicinal product See ISO/TS 20443 for more information and examples.
   */
  public status: fhir.CodeableConcept|null;
  /**
   * Default constructor for MarketingStatus - initializes any required elements to null if a value is not provided.
   */
  constructor(source:Partial<fhir.IMarketingStatus> = {}) {
    super(source);
    this.country = null;
    if (source["country"]) { this.country = new fhir.CodeableConcept(source.country!); }
    if (this.country === undefined) { this.country = null }
    this.dateRange = null;
    if (source["dateRange"]) { this.dateRange = new fhir.Period(source.dateRange!); }
    if (this.dateRange === undefined) { this.dateRange = null }
    if (source["jurisdiction"]) { this.jurisdiction = new fhir.CodeableConcept(source.jurisdiction!); }
    if (source["restoreDate"]) { this.restoreDate = source.restoreDate; }
    if (source["_restoreDate"]) { this._restoreDate = new fhir.FhirElement(source._restoreDate!); }
    this.status = null;
    if (source["status"]) { this.status = new fhir.CodeableConcept(source.status!); }
    if (this.status === undefined) { this.status = null }
  }
  /**
   * Check if the current MarketingStatus contains all required elements.
   */
  override CheckRequiredElements():string[] {
    var missingElements:string[] = [];
    if (this["country"] === undefined) { missingElements.push("country"); }
    if (this["dateRange"] === undefined) { missingElements.push("dateRange"); }
    if (this["status"] === undefined) { missingElements.push("status"); }
    var parentMissing:string[] = super.CheckRequiredElements();
    missingElements.push(...parentMissing);
    return missingElements;
  }
  /**
   * Factory function to create a MarketingStatus from an object that MUST contain all required elements.
   */
  static override FromStrict(source:fhir.IMarketingStatus):MarketingStatus {
    var dest:MarketingStatus = new MarketingStatus(source);
    var missingElements:string[] = dest.CheckRequiredElements();
    if (missingElements.length !== 0) { throw `MarketingStatus is missing elements: ${missingElements.join(", ")}` }
    return dest;
  }
}
