var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Primitive Naming Style: None
// Complex Type / Resource Naming Style: PascalCase
// Interaction Naming Style: None
// Extension Support: NonPrimitive
// Minimum TypeScript Version: 3.7
import * as fhirModels from '../optionalmodels';
/**
 * A contributor to the content of a knowledge asset, including authors, editors, reviewers, and endorsers.
 */
var Contributor = /** @class */ (function (_super) {
    __extends(Contributor, _super);
    /**
     * Default constructor for Contributor from an object that MAY NOT contain all required elements.
     */
    function Contributor(source) {
        var _this = _super.call(this, source) || this;
        if (source["contact"] !== undefined) {
            _this.contact = source.contact.map(function (x) { return new fhirModels.ContactDetail(x); });
        }
        if (source["name"] !== undefined) {
            _this.name = source.name;
        }
        if (source["_name"] !== undefined) {
            _this._name = new fhirModels.Element(source._name);
        }
        if (source["type"] !== undefined) {
            _this.type = source.type;
        }
        if (source["_type"] !== undefined) {
            _this._type = new fhirModels.Element(source._type);
        }
        return _this;
    }
    /**
     * Factory function to create a Contributor from an object that MUST contain all required elements.
     */
    Contributor.CreateStrict = function (source) {
        var dest = new Contributor(source);
        var missingElements = dest.checkRequiredElements();
        if (missingElements.length !== 0) {
            throw "Contributor is missing elements: ".concat(missingElements.join(", "));
        }
        return dest;
    };
    /**
     * Check if the current Contributor contains all required elements.
     */
    Contributor.prototype.checkRequiredElements = function () {
        var missingElements = [];
        if (this["name"] === undefined) {
            missingElements.push("name");
        }
        if (this["type"] === undefined) {
            missingElements.push("type");
        }
        var parentMissing = _super.prototype.checkRequiredElements.call(this);
        missingElements.push.apply(missingElements, parentMissing);
        return missingElements;
    };
    return Contributor;
}(fhirModels.Element));
export { Contributor };
/**
 * Code Values for the Contributor.type field
 */
export var ContributorTypeEnum;
(function (ContributorTypeEnum) {
    ContributorTypeEnum["AUTHOR"] = "author";
    ContributorTypeEnum["EDITOR"] = "editor";
    ContributorTypeEnum["REVIEWER"] = "reviewer";
    ContributorTypeEnum["ENDORSER"] = "endorser";
})(ContributorTypeEnum || (ContributorTypeEnum = {}));
