import { Coding } from '../strictmodels';
/**
 * This value set includes some method codes from SNOMED CT - provided as an exemplar
 */
export declare const AdministrationMethodCodes: {
    AdministrationMethodCodes_Apply: Coding;
    AdministrationMethodCodes_Administer: Coding;
    AdministrationMethodCodes_Use: Coding;
    AdministrationMethodCodes_Give: Coding;
    AdministrationMethodCodes_Take: Coding;
    AdministrationMethodCodes_Chew: Coding;
    AdministrationMethodCodes_Suck: Coding;
    AdministrationMethodCodes_At: Coding;
    AdministrationMethodCodes_DosingInstructionImperative: Coding;
    AdministrationMethodCodes_Only: Coding;
    AdministrationMethodCodes_Constant: Coding;
    AdministrationMethodCodes_Sniff: Coding;
    AdministrationMethodCodes_SubtractDosingInstructionFragment: Coding;
    AdministrationMethodCodes_As: Coding;
    AdministrationMethodCodes_Or: Coding;
    AdministrationMethodCodes_Finish: Coding;
    AdministrationMethodCodes_Shampoo: Coding;
    AdministrationMethodCodes_Push: Coding;
    AdministrationMethodCodes_UntilGone: Coding;
    AdministrationMethodCodes_Upon: Coding;
    AdministrationMethodCodes_Per: Coding;
    AdministrationMethodCodes_Sparingly: Coding;
    AdministrationMethodCodes_Call: Coding;
    AdministrationMethodCodes_When: Coding;
    AdministrationMethodCodes_To: Coding;
    AdministrationMethodCodes_Place: Coding;
    AdministrationMethodCodes_Then: Coding;
    AdministrationMethodCodes_Inhale: Coding;
    AdministrationMethodCodes_Hold: Coding;
    AdministrationMethodCodes_Multiply: Coding;
    AdministrationMethodCodes_Insert: Coding;
    AdministrationMethodCodes_Discontinue: Coding;
    AdministrationMethodCodes_SwishAndSwallow: Coding;
    AdministrationMethodCodes_Dilute: Coding;
    AdministrationMethodCodes_With: Coding;
    AdministrationMethodCodes_ThenDiscontinue: Coding;
    AdministrationMethodCodes_Swallow: Coding;
    AdministrationMethodCodes_Instill: Coding;
    AdministrationMethodCodes_Until: Coding;
    AdministrationMethodCodes_Every: Coding;
    AdministrationMethodCodes_Dissolve: Coding;
    AdministrationMethodCodes_Before: Coding;
    AdministrationMethodCodes_Now: Coding;
    AdministrationMethodCodes_FollowDirections: Coding;
    AdministrationMethodCodes_If: Coding;
    AdministrationMethodCodes_Swish: Coding;
    AdministrationMethodCodes_And: Coding;
    AdministrationMethodCodes_Twice: Coding;
    AdministrationMethodCodes_Follow: Coding;
    AdministrationMethodCodes_UntilFinished: Coding;
    AdministrationMethodCodes_During: Coding;
    AdministrationMethodCodes_Divide: Coding;
    AdministrationMethodCodes_Add: Coding;
    AdministrationMethodCodes_Once: Coding;
    AdministrationMethodCodes_Inject: Coding;
    AdministrationMethodCodes_Wash: Coding;
    AdministrationMethodCodes_Sprinkle: Coding;
    AdministrationMethodCodes_ThenStop: Coding;
};
//# sourceMappingURL=AdministrationMethodCodes.d.ts.map