// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
  // Primitive Naming Style: None
  // Complex Type / Resource Naming Style: PascalCase
  // Interaction Naming Style: None
  // Extension Support: NonPrimitive
// Minimum TypeScript Version: 3.7
import { Coding } from '../models'
/**
 * Code of parameter that is input to the guide.
 */
export const GuideParameterCode = {
  /**
   * If the value of this string 0..* parameter is one of the metadata fields then all conformance resources will have any specified [Resource].[field] overwritten with the ImplementationGuide.[field], where field is one of: version, date, status, publisher, contact, copyright, experimental, jurisdiction, useContext.
   */
  guide_parameter_code_ApplyMetadataValue: {
    code: "apply",
    display: "Apply Metadata Value",
    system: "http://hl7.org/fhir/guide-parameter-code"
  } as Coding,
  /**
   * The value of this string 0..* parameter is a parameter (name=value) when expanding value sets for this implementation guide. This is particularly used to specify the versions of published terminologies such as SNOMED CT.
   */
  guide_parameter_code_ExpansionProfile: {
    code: "expansion-parameter",
    display: "Expansion Profile",
    system: "http://hl7.org/fhir/guide-parameter-code"
  } as Coding,
  /**
   * The value of this boolean 0..1 parameter specifies whether the IG publisher creates examples in JSON format. If not present, the Publication Tool decides whether to generate JSON.
   */
  guide_parameter_code_GenerateJSON: {
    code: "generate-json",
    display: "Generate JSON",
    system: "http://hl7.org/fhir/guide-parameter-code"
  } as Coding,
  /**
   * The value of this boolean 0..1 parameter specifies whether the IG publisher creates examples in Turtle format. If not present, the Publication Tool decides whether to generate Turtle.
   */
  guide_parameter_code_GenerateTurtle: {
    code: "generate-turtle",
    display: "Generate Turtle",
    system: "http://hl7.org/fhir/guide-parameter-code"
  } as Coding,
  /**
   * The value of this boolean 0..1 parameter specifies whether the IG publisher creates examples in XML format. If not present, the Publication Tool decides whether to generate XML.
   */
  guide_parameter_code_GenerateXML: {
    code: "generate-xml",
    display: "Generate XML",
    system: "http://hl7.org/fhir/guide-parameter-code"
  } as Coding,
  /**
   * The value of this string singleton parameter is the name of the file to use as the builder template for each generated page (see templating).
   */
  guide_parameter_code_HTMLTemplate: {
    code: "html-template",
    display: "HTML Template",
    system: "http://hl7.org/fhir/guide-parameter-code"
  } as Coding,
  /**
   * The value of this string 0..1 parameter is a subfolder of the build context's location that contains files that are part of the html content processed by the builder.
   */
  guide_parameter_code_PagesPath: {
    code: "path-pages",
    display: "Pages Path",
    system: "http://hl7.org/fhir/guide-parameter-code"
  } as Coding,
  /**
   * The value of this string 0..* parameter is a subfolder of the build context's location that is to be scanned to load resources. Scope is (if present) a particular resource type.
   */
  guide_parameter_code_ResourcePath: {
    code: "path-resource",
    display: "Resource Path",
    system: "http://hl7.org/fhir/guide-parameter-code"
  } as Coding,
  /**
   * The value of this string 0..1 parameter is a subfolder of the build context's location that is used as the terminology cache. If this is not present, the terminology cache is on the local system, not under version control.
   */
  guide_parameter_code_TerminologyCachePath: {
    code: "path-tx-cache",
    display: "Terminology Cache Path",
    system: "http://hl7.org/fhir/guide-parameter-code"
  } as Coding,
  /**
   * The value of this string 0..1 parameter is either "warning" or "error" (default = "error"). If the value is "warning" then IG build tools allow the IG to be considered successfully build even when there is no internal broken links.
   */
  guide_parameter_code_BrokenLinksRule: {
    code: "rule-broken-links",
    display: "Broken Links Rule",
    system: "http://hl7.org/fhir/guide-parameter-code"
  } as Coding,
};
