// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Enum: http://hl7.org/fhir/ValueSet/benefit-term|4.0.1

/**
 * This value set includes a smattering of Benefit Term codes.
 */
export enum BenefitTermValueSetEnum {
  /**
   * annual: Annual, renewing on the anniversary
   */
  Annual = "annual",
  /**
   * day: Per day
   */
  Day = "day",
  /**
   * lifetime: For the total term, lifetime, of the policy or coverage
   */
  Lifetime = "lifetime",
}
