// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
  // Primitive Naming Style: None
  // Complex Type / Resource Naming Style: PascalCase
  // Interaction Naming Style: None
  // Extension Support: NonPrimitive
// Minimum TypeScript Version: 3.7
import { Coding } from '../fhir'
/**
 * Example use codes for the List resource - typical kinds of use.
 */
export const ListExampleCodesValueSet = {
  /**
   * A list of part adverse reactions.
   */
  list_example_codes_AdverseReactions: Coding.FromStrict({
    code: "adverserxns",
    display: "Adverse Reactions",
    system: "http://terminology.hl7.org/CodeSystem/list-example-use-codes"
  }),
  /**
   * A list of alerts for the patient.
   */
  list_example_codes_Alerts: Coding.FromStrict({
    code: "alerts",
    display: "Alerts",
    system: "http://terminology.hl7.org/CodeSystem/list-example-use-codes"
  }),
  /**
   * A list of Allergies for the patient.
   */
  list_example_codes_Allergies: Coding.FromStrict({
    code: "allergies",
    display: "Allergies",
    system: "http://terminology.hl7.org/CodeSystem/list-example-use-codes"
  }),
  /**
   * A list of medication statements for the patient.
   */
  list_example_codes_MedicationList: Coding.FromStrict({
    code: "medications",
    display: "Medication List",
    system: "http://terminology.hl7.org/CodeSystem/list-example-use-codes"
  }),
  /**
   * A set of care plans that apply in a particular context of care.
   */
  list_example_codes_CarePlans: Coding.FromStrict({
    code: "plans",
    display: "Care Plans",
    system: "http://terminology.hl7.org/CodeSystem/list-example-use-codes"
  }),
  /**
   * A list of problems that the patient is known of have (or have had in the past).
   */
  list_example_codes_ProblemList: Coding.FromStrict({
    code: "problems",
    display: "Problem List",
    system: "http://terminology.hl7.org/CodeSystem/list-example-use-codes"
  }),
  /**
   * A set of protocols to be followed.
   */
  list_example_codes_Protocols: Coding.FromStrict({
    code: "protocols",
    display: "Protocols",
    system: "http://terminology.hl7.org/CodeSystem/list-example-use-codes"
  }),
  /**
   * A list of items waiting for an event (perhaps a surgical patient waiting list).
   */
  list_example_codes_WaitingList: Coding.FromStrict({
    code: "waiting",
    display: "Waiting List",
    system: "http://terminology.hl7.org/CodeSystem/list-example-use-codes"
  }),
  /**
   * A list of items that constitute a set of work to be performed (typically this code would be specialized for more specific uses, such as a ward round list).
   */
  list_example_codes_Worklist: Coding.FromStrict({
    code: "worklist",
    display: "Worklist",
    system: "http://terminology.hl7.org/CodeSystem/list-example-use-codes"
  }),
};
