// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
  // Primitive Naming Style: None
  // Complex Type / Resource Naming Style: PascalCase
  // Interaction Naming Style: None
  // Extension Support: NonPrimitive
// Minimum TypeScript Version: 3.7
import { Coding } from '../fhir'
/**
 * This value set includes all dose form codes from SNOMED CT - provided as an exemplar.
 */
export const MedicationFormCodesValueSet = {
  MedicationFormCodesValueSet_DrugStick: Coding.FromStrict({
    code: "11190007",
    display: "Drug stick",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Lotion: Coding.FromStrict({
    code: "17519006",
    display: "Lotion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DrugAerosolFoam: Coding.FromStrict({
    code: "30843009",
    display: "Drug aerosol foam",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DrugPatch: Coding.FromStrict({
    code: "36875001",
    display: "Drug patch",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DrugPaste: Coding.FromStrict({
    code: "37937005",
    display: "Drug paste",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralDrops: Coding.FromStrict({
    code: "385018001",
    display: "Oral drops",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralDropsSolution: Coding.FromStrict({
    code: "385019009",
    display: "Oral drops solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralDropsSuspension: Coding.FromStrict({
    code: "385020003",
    display: "Oral drops suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralDropsEmulsion: Coding.FromStrict({
    code: "385021004",
    display: "Oral drops emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralLiquid: Coding.FromStrict({
    code: "385022006",
    display: "Oral liquid",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralSolution: Coding.FromStrict({
    code: "385023001",
    display: "Oral solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralSuspension: Coding.FromStrict({
    code: "385024007",
    display: "Oral suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralEmulsion: Coding.FromStrict({
    code: "385025008",
    display: "Oral emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForOralSolution: Coding.FromStrict({
    code: "385026009",
    display: "Powder for oral solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForOralSuspension: Coding.FromStrict({
    code: "385027000",
    display: "Powder for oral suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GranulesForOralSolution: Coding.FromStrict({
    code: "385028005",
    display: "Granules for oral solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GranulesForOralSuspension: Coding.FromStrict({
    code: "385029002",
    display: "Granules for oral suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Syrup: Coding.FromStrict({
    code: "385032004",
    display: "Syrup",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForSyrup: Coding.FromStrict({
    code: "385033009",
    display: "Powder for syrup",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GranulesForSyrup: Coding.FromStrict({
    code: "385034003",
    display: "Granules for syrup",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SolubleTablet: Coding.FromStrict({
    code: "385035002",
    display: "Soluble tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DispersibleTablet: Coding.FromStrict({
    code: "385036001",
    display: "Dispersible tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralGel: Coding.FromStrict({
    code: "385038000",
    display: "Oral gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralPaste: Coding.FromStrict({
    code: "385039008",
    display: "Oral paste",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralPowder: Coding.FromStrict({
    code: "385041009",
    display: "Oral powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EffervescentPowder: Coding.FromStrict({
    code: "385042002",
    display: "Effervescent powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Granules: Coding.FromStrict({
    code: "385043007",
    display: "Granules",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EffervescentGranules: Coding.FromStrict({
    code: "385044001",
    display: "Effervescent granules",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GastroResistantGranules: Coding.FromStrict({
    code: "385045000",
    display: "Gastro-resistant granules",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ProlongedReleaseGranules: Coding.FromStrict({
    code: "385046004",
    display: "Prolonged-release granules",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ModifiedReleaseGranules: Coding.FromStrict({
    code: "385047008",
    display: "Modified-release granules",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Cachet: Coding.FromStrict({
    code: "385048003",
    display: "Cachet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Capsule: Coding.FromStrict({
    code: "385049006",
    display: "Capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_HardCapsule: Coding.FromStrict({
    code: "385050006",
    display: "Hard capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SoftCapsule: Coding.FromStrict({
    code: "385051005",
    display: "Soft capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GastroResistantCapsule: Coding.FromStrict({
    code: "385052003",
    display: "Gastro-resistant capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ProlongedReleaseCapsule: Coding.FromStrict({
    code: "385053008",
    display: "Prolonged-release capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ModifiedReleaseCapsule: Coding.FromStrict({
    code: "385054002",
    display: "Modified-release capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Tablet: Coding.FromStrict({
    code: "385055001",
    display: "Tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_FilmCoatedTablet: Coding.FromStrict({
    code: "385057009",
    display: "Film-coated tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EffervescentTablet: Coding.FromStrict({
    code: "385058004",
    display: "Effervescent tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GastroResistantTablet: Coding.FromStrict({
    code: "385059007",
    display: "Gastro-resistant tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ProlongedReleaseTablet: Coding.FromStrict({
    code: "385060002",
    display: "Prolonged-release tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ModifiedReleaseTablet: Coding.FromStrict({
    code: "385061003",
    display: "Modified-release tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralLyophilisate: Coding.FromStrict({
    code: "385062005",
    display: "Oral lyophilisate",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralGum: Coding.FromStrict({
    code: "385063000",
    display: "Oral gum",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Pillule: Coding.FromStrict({
    code: "385064006",
    display: "Pillule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OromucosalLiquid: Coding.FromStrict({
    code: "385069001",
    display: "Oromucosal liquid",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OromucosalSolution: Coding.FromStrict({
    code: "385070000",
    display: "Oromucosal solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OromucosalSuspension: Coding.FromStrict({
    code: "385071001",
    display: "Oromucosal suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OromucosalSpray: Coding.FromStrict({
    code: "385073003",
    display: "Oromucosal spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SublingualSpray: Coding.FromStrict({
    code: "385074009",
    display: "Sublingual spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GingivalSolution: Coding.FromStrict({
    code: "385077002",
    display: "Gingival solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OromucosalGel: Coding.FromStrict({
    code: "385078007",
    display: "Oromucosal gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OromucosalPaste: Coding.FromStrict({
    code: "385079004",
    display: "Oromucosal paste",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MedicatedChewingGum: Coding.FromStrict({
    code: "385080001",
    display: "Medicated chewing-gum",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GingivalGel: Coding.FromStrict({
    code: "385081002",
    display: "Gingival gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GingivalPaste: Coding.FromStrict({
    code: "385082009",
    display: "Gingival paste",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OromucosalCapsule: Coding.FromStrict({
    code: "385083004",
    display: "Oromucosal capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SublingualTablet: Coding.FromStrict({
    code: "385084005",
    display: "Sublingual tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_BuccalTablet: Coding.FromStrict({
    code: "385085006",
    display: "Buccal tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MucoAdhesiveBuccalTablet: Coding.FromStrict({
    code: "385086007",
    display: "Muco-adhesive buccal tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Lozenge: Coding.FromStrict({
    code: "385087003",
    display: "Lozenge",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DentalGel: Coding.FromStrict({
    code: "385088008",
    display: "Dental gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DentalStick: Coding.FromStrict({
    code: "385089000",
    display: "Dental stick",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DentalInsert: Coding.FromStrict({
    code: "385090009",
    display: "Dental insert",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DentalPowder: Coding.FromStrict({
    code: "385091008",
    display: "Dental powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DentalLiquid: Coding.FromStrict({
    code: "385092001",
    display: "Dental liquid",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DentalSolution: Coding.FromStrict({
    code: "385094000",
    display: "Dental solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DentalSuspension: Coding.FromStrict({
    code: "385095004",
    display: "Dental suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DentalEmulsion: Coding.FromStrict({
    code: "385096003",
    display: "Dental emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_BathAdditive: Coding.FromStrict({
    code: "385098002",
    display: "Bath additive",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Cream: Coding.FromStrict({
    code: "385099005",
    display: "Cream",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Gel: Coding.FromStrict({
    code: "385100002",
    display: "Gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Ointment: Coding.FromStrict({
    code: "385101003",
    display: "Ointment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousPaste: Coding.FromStrict({
    code: "385102005",
    display: "Cutaneous paste",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousFoam: Coding.FromStrict({
    code: "385103000",
    display: "Cutaneous foam",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Shampoo: Coding.FromStrict({
    code: "385104006",
    display: "Shampoo",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousSpray: Coding.FromStrict({
    code: "385105007",
    display: "Cutaneous spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousSolutionSpray: Coding.FromStrict({
    code: "385106008",
    display: "Cutaneous solution spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousLiquid: Coding.FromStrict({
    code: "385107004",
    display: "Cutaneous liquid",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousSolution: Coding.FromStrict({
    code: "385108009",
    display: "Cutaneous solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousSuspension: Coding.FromStrict({
    code: "385110006",
    display: "Cutaneous suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousEmulsion: Coding.FromStrict({
    code: "385111005",
    display: "Cutaneous emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousPowder: Coding.FromStrict({
    code: "385112003",
    display: "Cutaneous powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SolutionForIontophoresis: Coding.FromStrict({
    code: "385113008",
    display: "Solution for iontophoresis",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_TransdermalPatch: Coding.FromStrict({
    code: "385114002",
    display: "Transdermal patch",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Collodion: Coding.FromStrict({
    code: "385115001",
    display: "Collodion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MedicatedNailLaquer: Coding.FromStrict({
    code: "385116000",
    display: "Medicated nail laquer",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Poultice: Coding.FromStrict({
    code: "385117009",
    display: "Poultice",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousStick: Coding.FromStrict({
    code: "385118004",
    display: "Cutaneous stick",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousSponge: Coding.FromStrict({
    code: "385119007",
    display: "Cutaneous sponge",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeCream: Coding.FromStrict({
    code: "385121002",
    display: "Eye cream",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeGel: Coding.FromStrict({
    code: "385122009",
    display: "Eye gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeOintment: Coding.FromStrict({
    code: "385123004",
    display: "Eye ointment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeDrops: Coding.FromStrict({
    code: "385124005",
    display: "Eye drops",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeDropsSolution: Coding.FromStrict({
    code: "385125006",
    display: "Eye drops solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ProlongedReleaseEyeDrops: Coding.FromStrict({
    code: "385128008",
    display: "Prolonged-release eye drops",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeLotion: Coding.FromStrict({
    code: "385130005",
    display: "Eye lotion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OphthalmicInsert: Coding.FromStrict({
    code: "385132002",
    display: "Ophthalmic insert",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarCream: Coding.FromStrict({
    code: "385133007",
    display: "Ear cream",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarGel: Coding.FromStrict({
    code: "385134001",
    display: "Ear gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarOintment: Coding.FromStrict({
    code: "385135000",
    display: "Ear ointment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarDrops: Coding.FromStrict({
    code: "385136004",
    display: "Ear drops",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarDropsSolution: Coding.FromStrict({
    code: "385137008",
    display: "Ear drops solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarDropsEmulsion: Coding.FromStrict({
    code: "385138003",
    display: "Ear drops emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarPowder: Coding.FromStrict({
    code: "385139006",
    display: "Ear powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarSpray: Coding.FromStrict({
    code: "385140008",
    display: "Ear spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarSpraySolution: Coding.FromStrict({
    code: "385141007",
    display: "Ear spray solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarSpraySuspension: Coding.FromStrict({
    code: "385142000",
    display: "Ear spray suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarSprayEmulsion: Coding.FromStrict({
    code: "385143005",
    display: "Ear spray emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarTampon: Coding.FromStrict({
    code: "385147006",
    display: "Ear tampon",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarStick: Coding.FromStrict({
    code: "385148001",
    display: "Ear stick",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalCream: Coding.FromStrict({
    code: "385149009",
    display: "Nasal cream",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalGel: Coding.FromStrict({
    code: "385150009",
    display: "Nasal gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalOintment: Coding.FromStrict({
    code: "385151008",
    display: "Nasal ointment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalDrops: Coding.FromStrict({
    code: "385152001",
    display: "Nasal drops",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalDropsSolution: Coding.FromStrict({
    code: "385153006",
    display: "Nasal drops solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalDropsSuspension: Coding.FromStrict({
    code: "385154000",
    display: "Nasal drops suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalDropsEmulsion: Coding.FromStrict({
    code: "385155004",
    display: "Nasal drops emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalPowder: Coding.FromStrict({
    code: "385156003",
    display: "Nasal powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalSpray: Coding.FromStrict({
    code: "385157007",
    display: "Nasal spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalSpraySolution: Coding.FromStrict({
    code: "385158002",
    display: "Nasal spray solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalSpraySuspension: Coding.FromStrict({
    code: "385159005",
    display: "Nasal spray suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalSprayEmulsion: Coding.FromStrict({
    code: "385160000",
    display: "Nasal spray emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalStick: Coding.FromStrict({
    code: "385162008",
    display: "Nasal stick",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeEarNoseDrops: Coding.FromStrict({
    code: "385163003",
    display: "Eye/ear/nose drops",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeEarNoseOintment: Coding.FromStrict({
    code: "385164009",
    display: "Eye/ear/nose ointment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalCream: Coding.FromStrict({
    code: "385165005",
    display: "Vaginal cream",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalGel: Coding.FromStrict({
    code: "385166006",
    display: "Vaginal gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalOintment: Coding.FromStrict({
    code: "385167002",
    display: "Vaginal ointment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalFoam: Coding.FromStrict({
    code: "385168007",
    display: "Vaginal foam",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalLiquid: Coding.FromStrict({
    code: "385169004",
    display: "Vaginal liquid",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalSolution: Coding.FromStrict({
    code: "385170003",
    display: "Vaginal solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalSuspension: Coding.FromStrict({
    code: "385171004",
    display: "Vaginal suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalEmulsion: Coding.FromStrict({
    code: "385172006",
    display: "Vaginal emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_TabletForVaginalSolution: Coding.FromStrict({
    code: "385173001",
    display: "Tablet for vaginal solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Pessary: Coding.FromStrict({
    code: "385174007",
    display: "Pessary",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalCapsule: Coding.FromStrict({
    code: "385175008",
    display: "Vaginal capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_HardVaginalCapsule: Coding.FromStrict({
    code: "385176009",
    display: "Hard vaginal capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SoftVaginalCapsule: Coding.FromStrict({
    code: "385177000",
    display: "Soft vaginal capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalTablet: Coding.FromStrict({
    code: "385178005",
    display: "Vaginal tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EffervescentVaginalTablet: Coding.FromStrict({
    code: "385179002",
    display: "Effervescent vaginal tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MedicatedVaginalTampon: Coding.FromStrict({
    code: "385180004",
    display: "Medicated vaginal tampon",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalCream: Coding.FromStrict({
    code: "385182007",
    display: "Rectal cream",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalGel: Coding.FromStrict({
    code: "385183002",
    display: "Rectal gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalOintment: Coding.FromStrict({
    code: "385184008",
    display: "Rectal ointment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalFoam: Coding.FromStrict({
    code: "385185009",
    display: "Rectal foam",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Enema: Coding.FromStrict({
    code: "385186005",
    display: "Enema",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalSolution: Coding.FromStrict({
    code: "385187001",
    display: "Rectal solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalSuspension: Coding.FromStrict({
    code: "385188006",
    display: "Rectal suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalEmulsion: Coding.FromStrict({
    code: "385189003",
    display: "Rectal emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForRectalSuspension: Coding.FromStrict({
    code: "385191006",
    display: "Powder for rectal suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_TabletForRectalSolution: Coding.FromStrict({
    code: "385192004",
    display: "Tablet for rectal solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_TabletForRectalSuspension: Coding.FromStrict({
    code: "385193009",
    display: "Tablet for rectal suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Suppository: Coding.FromStrict({
    code: "385194003",
    display: "Suppository",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalCapsule: Coding.FromStrict({
    code: "385195002",
    display: "Rectal capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalTampon: Coding.FromStrict({
    code: "385196001",
    display: "Rectal tampon",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NebulizerLiquid: Coding.FromStrict({
    code: "385197005",
    display: "Nebulizer liquid",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NebulizerSolution: Coding.FromStrict({
    code: "385198000",
    display: "Nebulizer solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NebulizerSuspension: Coding.FromStrict({
    code: "385199008",
    display: "Nebulizer suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForNebulizerSuspension: Coding.FromStrict({
    code: "385200006",
    display: "Powder for nebulizer suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForNebulizerSolution: Coding.FromStrict({
    code: "385201005",
    display: "Powder for nebulizer solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NebulizerEmulsion: Coding.FromStrict({
    code: "385202003",
    display: "Nebulizer emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PressurisedInhalation: Coding.FromStrict({
    code: "385203008",
    display: "Pressurised inhalation",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PressurisedInhalationSolution: Coding.FromStrict({
    code: "385204002",
    display: "Pressurised inhalation solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PressurisedInhalationSuspension: Coding.FromStrict({
    code: "385205001",
    display: "Pressurised inhalation suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PressurisedInhalationEmulsion: Coding.FromStrict({
    code: "385206000",
    display: "Pressurised inhalation emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationPowder: Coding.FromStrict({
    code: "385207009",
    display: "Inhalation powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_HardCapsuleInhalationPowder: Coding.FromStrict({
    code: "385208004",
    display: "Hard capsule inhalation powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationVapor: Coding.FromStrict({
    code: "385210002",
    display: "Inhalation vapor",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationVaporPowder: Coding.FromStrict({
    code: "385211003",
    display: "Inhalation vapor powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationVaporCapsule: Coding.FromStrict({
    code: "385212005",
    display: "Inhalation vapor capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationVaporSolution: Coding.FromStrict({
    code: "385213000",
    display: "Inhalation vapor solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationVaporTablet: Coding.FromStrict({
    code: "385214006",
    display: "Inhalation vapor tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationVaporOintment: Coding.FromStrict({
    code: "385215007",
    display: "Inhalation vapor ointment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationVaporLiquid: Coding.FromStrict({
    code: "385216008",
    display: "Inhalation vapor liquid",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationGas: Coding.FromStrict({
    code: "385217004",
    display: "Inhalation gas",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InjectionSolution: Coding.FromStrict({
    code: "385219001",
    display: "Injection solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InjectionSuspension: Coding.FromStrict({
    code: "385220007",
    display: "Injection suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InjectionEmulsion: Coding.FromStrict({
    code: "385221006",
    display: "Injection emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InjectionPowder: Coding.FromStrict({
    code: "385222004",
    display: "Injection powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForInjectionSolution: Coding.FromStrict({
    code: "385223009",
    display: "Powder for injection solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForInjectionSuspension: Coding.FromStrict({
    code: "385224003",
    display: "Powder for injection suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InfusionSolution: Coding.FromStrict({
    code: "385229008",
    display: "Infusion solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InfusionPowder: Coding.FromStrict({
    code: "385230003",
    display: "Infusion powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForInfusionSolution: Coding.FromStrict({
    code: "385231004",
    display: "Powder for infusion solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ImplantationTablet: Coding.FromStrict({
    code: "385236009",
    display: "Implantation tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ImplantationChain: Coding.FromStrict({
    code: "385237000",
    display: "Implantation chain",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_IntravesicalSolution: Coding.FromStrict({
    code: "385242008",
    display: "Intravesical solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_UrethralGel: Coding.FromStrict({
    code: "385245005",
    display: "Urethral gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_UrethralStick: Coding.FromStrict({
    code: "385246006",
    display: "Urethral stick",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EndotracheopulmonaryInstillationSolution: Coding.FromStrict({
    code: "385247002",
    display: "Endotracheopulmonary instillation solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForEndotracheopulmonaryInstillationSolution: Coding.FromStrict({
    code: "385248007",
    display: "Powder for endotracheopulmonary instillation solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EndotracheopulmonaryInstillationSuspension: Coding.FromStrict({
    code: "385250004",
    display: "Endotracheopulmonary instillation suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EndocervicalGel: Coding.FromStrict({
    code: "385251000",
    display: "Endocervical gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GastroenteralLiquid: Coding.FromStrict({
    code: "385257001",
    display: "Gastroenteral liquid",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GastroenteralSolution: Coding.FromStrict({
    code: "385258006",
    display: "Gastroenteral solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GastroenteralSuspension: Coding.FromStrict({
    code: "385259003",
    display: "Gastroenteral suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GastroenteralEmulsion: Coding.FromStrict({
    code: "385260008",
    display: "Gastroenteral emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_WoundStick: Coding.FromStrict({
    code: "385261007",
    display: "Wound stick",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OrganPreservationSolution: Coding.FromStrict({
    code: "385262000",
    display: "Organ preservation solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousPowderSpray: Coding.FromStrict({
    code: "385278003",
    display: "Cutaneous powder spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousSuspensionSpray: Coding.FromStrict({
    code: "385279006",
    display: "Cutaneous suspension spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ImplantDosageForm: Coding.FromStrict({
    code: "385286003",
    display: "Implant dosage form",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralElixir: Coding.FromStrict({
    code: "414951009",
    display: "Oral elixir",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_TamponDoseForm: Coding.FromStrict({
    code: "420243009",
    display: "Tampon dose form",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OilInjection: Coding.FromStrict({
    code: "420253005",
    display: "Oil injection",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SemiSolidDoseForm: Coding.FromStrict({
    code: "420275007",
    display: "Semi-solid dose form",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalEmulsion: Coding.FromStrict({
    code: "420283001",
    display: "Nasal emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalPowder: Coding.FromStrict({
    code: "420292003",
    display: "Rectal powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CoatedPelletsCapsule: Coding.FromStrict({
    code: "420293008",
    display: "Coated pellets capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForOralLiquid: Coding.FromStrict({
    code: "420305009",
    display: "Powder for oral liquid",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Inhaler: Coding.FromStrict({
    code: "420317006",
    display: "Inhaler",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseFilmCoatedTablet: Coding.FromStrict({
    code: "420378007",
    display: "Extended-release film coated tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseInsert: Coding.FromStrict({
    code: "420385006",
    display: "Extended-release insert",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Emulsion: Coding.FromStrict({
    code: "420386007",
    display: "Emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationAerosolSolution: Coding.FromStrict({
    code: "420407000",
    display: "Inhalation aerosol solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_LyophilizedPowderForInjectableExtendedReleaseLiposomalSuspension: Coding.FromStrict({
    code: "420430006",
    display: "Lyophilized powder for injectable extended release liposomal suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PressurizedNebulizerSuspension: Coding.FromStrict({
    code: "420450005",
    display: "Pressurized nebulizer suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Film: Coding.FromStrict({
    code: "420460001",
    display: "Film",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralGranules: Coding.FromStrict({
    code: "420509004",
    display: "Oral granules",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalPowder: Coding.FromStrict({
    code: "420536002",
    display: "Vaginal powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousOil: Coding.FromStrict({
    code: "420540006",
    display: "Cutaneous oil",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalAerosol: Coding.FromStrict({
    code: "420610000",
    display: "Nasal aerosol",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseTablet: Coding.FromStrict({
    code: "420627008",
    display: "Extended-release tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalInsert: Coding.FromStrict({
    code: "420631002",
    display: "Vaginal insert",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MicrospheresForInjectableSuspension: Coding.FromStrict({
    code: "420634005",
    display: "Microspheres for injectable suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeEarDrops: Coding.FromStrict({
    code: "420636007",
    display: "Eye/ear drops",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SolutionForInhalation: Coding.FromStrict({
    code: "420641004",
    display: "Solution for inhalation",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_LyophilizedPowderForInjectableLiposomalSuspension: Coding.FromStrict({
    code: "420656008",
    display: "Lyophilized powder for injectable liposomal suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralCapsule: Coding.FromStrict({
    code: "420692007",
    display: "Oral capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_LiquidDoseForm: Coding.FromStrict({
    code: "420699003",
    display: "Liquid dose form",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InhalationAerosolSuspension: Coding.FromStrict({
    code: "420705007",
    display: "Inhalation aerosol suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeSuspension: Coding.FromStrict({
    code: "420736004",
    display: "Eye suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DelayedReleaseGranules: Coding.FromStrict({
    code: "420757007",
    display: "Delayed-release granules",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_UrethralSuppository: Coding.FromStrict({
    code: "420761001",
    display: "Urethral suppository",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DelayedReleasePelletsCapsule: Coding.FromStrict({
    code: "420767002",
    display: "Delayed-release pellets capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Pellet: Coding.FromStrict({
    code: "420768007",
    display: "Pellet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseLiquid: Coding.FromStrict({
    code: "420802004",
    display: "Extended-release liquid",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForReconstitutionForDrugProduct: Coding.FromStrict({
    code: "420828001",
    display: "Powder for reconstitution for drug product",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MeteredDoseAerosol: Coding.FromStrict({
    code: "420847003",
    display: "Metered dose aerosol",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseInjectableSuspension: Coding.FromStrict({
    code: "420873008",
    display: "Extended release injectable suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_IntrathecalSuspension: Coding.FromStrict({
    code: "420887008",
    display: "Intrathecal suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarDropsSuspension: Coding.FromStrict({
    code: "420891003",
    display: "Ear drops suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarEmulsion: Coding.FromStrict({
    code: "420901005",
    display: "Ear emulsion",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MeteredPowder: Coding.FromStrict({
    code: "420927005",
    display: "Metered powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalSuppository: Coding.FromStrict({
    code: "420929008",
    display: "Rectal suppository",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForSolution: Coding.FromStrict({
    code: "420955009",
    display: "Powder for solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_UltramicronizedTablet: Coding.FromStrict({
    code: "420956005",
    display: "Ultramicronized tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ImplantablePellet: Coding.FromStrict({
    code: "420992009",
    display: "Implantable pellet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralTablet: Coding.FromStrict({
    code: "421026006",
    display: "Oral tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DelayedReleaseCapsule: Coding.FromStrict({
    code: "421027002",
    display: "Delayed-release capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseSuppository: Coding.FromStrict({
    code: "421034000",
    display: "Extended-release suppository",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseFilm: Coding.FromStrict({
    code: "421043009",
    display: "Extended-release film",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SonicatedInjectableSuspension: Coding.FromStrict({
    code: "421051007",
    display: "Sonicated injectable suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EmulsionForInhalation: Coding.FromStrict({
    code: "421056002",
    display: "Emulsion for inhalation",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Pastille: Coding.FromStrict({
    code: "421079001",
    display: "Pastille",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForSuspension: Coding.FromStrict({
    code: "421080003",
    display: "Powder for suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_AerosolPowder: Coding.FromStrict({
    code: "421104008",
    display: "Aerosol powder",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_GaseousDoseForm: Coding.FromStrict({
    code: "421131006",
    display: "Gaseous dose form",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseEntericCoatedTablet: Coding.FromStrict({
    code: "421155001",
    display: "Extended-release enteric coated tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Foam: Coding.FromStrict({
    code: "421166008",
    display: "Foam",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalSuppository: Coding.FromStrict({
    code: "421195004",
    display: "Vaginal suppository",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SuspensionForInhalation: Coding.FromStrict({
    code: "421221008",
    display: "Suspension for inhalation",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseBeadImplant: Coding.FromStrict({
    code: "421271006",
    display: "Extended-release bead implant",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Sponge: Coding.FromStrict({
    code: "421288004",
    display: "Sponge",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseFilmCoatedCapsule: Coding.FromStrict({
    code: "421300005",
    display: "Extended-release film coated capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForEyeDrops: Coding.FromStrict({
    code: "421316007",
    display: "Powder for eye drops",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseCoatedCapsule: Coding.FromStrict({
    code: "421338009",
    display: "Extended-release coated capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderSpray: Coding.FromStrict({
    code: "421340004",
    display: "Powder spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForCutaneousSolution: Coding.FromStrict({
    code: "421343002",
    display: "Powder for cutaneous solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousAerosol: Coding.FromStrict({
    code: "421347001",
    display: "Cutaneous aerosol",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_TabletForOralSuspension: Coding.FromStrict({
    code: "421366001",
    display: "Tablet for oral suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DelayedReleaseTablet: Coding.FromStrict({
    code: "421374000",
    display: "Delayed-release tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SolidDoseForm: Coding.FromStrict({
    code: "421378002",
    display: "Solid dose form",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarSuspension: Coding.FromStrict({
    code: "421382000",
    display: "Ear suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_IntravenousSolution: Coding.FromStrict({
    code: "421410002",
    display: "Intravenous solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForInhalationSolution: Coding.FromStrict({
    code: "421425002",
    display: "Powder for inhalation solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeEarOintment: Coding.FromStrict({
    code: "421427005",
    display: "Eye/ear ointment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_InjectableOilSuspension: Coding.FromStrict({
    code: "421428000",
    display: "Injectable oil suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseGranulesForSuspension: Coding.FromStrict({
    code: "421446006",
    display: "Extended-release granules for suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Cone: Coding.FromStrict({
    code: "421504000",
    display: "Cone",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_LiposomalInjectableSuspension: Coding.FromStrict({
    code: "421522002",
    display: "Liposomal injectable suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Insert: Coding.FromStrict({
    code: "421532009",
    display: "Insert",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DelayedReleaseParticlesTablet: Coding.FromStrict({
    code: "421535006",
    display: "Delayed-release particles tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForEarDrops: Coding.FromStrict({
    code: "421575003",
    display: "Powder for ear drops",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_AerosolSpray: Coding.FromStrict({
    code: "421606006",
    display: "Aerosol spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForNasalDrops: Coding.FromStrict({
    code: "421607002",
    display: "Powder for nasal drops",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseCapsule: Coding.FromStrict({
    code: "421618002",
    display: "Extended-release capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SustainedReleaseBuccalTablet: Coding.FromStrict({
    code: "421620004",
    display: "Sustained-release buccal tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousCream: Coding.FromStrict({
    code: "421628006",
    display: "Cutaneous cream",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_LyophilizedPowderForInjectableSolution: Coding.FromStrict({
    code: "421637006",
    display: "Lyophilized powder for injectable solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MeteredGel: Coding.FromStrict({
    code: "421669002",
    display: "Metered gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_TabletForOralSolution: Coding.FromStrict({
    code: "421701006",
    display: "Tablet for oral solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EarSolution: Coding.FromStrict({
    code: "421713001",
    display: "Ear solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_TransdermalDrugDeliverySystem: Coding.FromStrict({
    code: "421716009",
    display: "Transdermal drug delivery system",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_SprayDoseForm: Coding.FromStrict({
    code: "421720008",
    display: "Spray dose form",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CoatedParticlesTablet: Coding.FromStrict({
    code: "421721007",
    display: "Coated particles tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseEntericCoatedCapsule: Coding.FromStrict({
    code: "421752008",
    display: "Extended-release enteric coated capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MeteredDoseAerosolInhaler: Coding.FromStrict({
    code: "421759004",
    display: "Metered dose aerosol inhaler",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_IntraperitonealSolution: Coding.FromStrict({
    code: "421765004",
    display: "Intraperitoneal solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForOphthalmicSolution: Coding.FromStrict({
    code: "421857007",
    display: "Powder for ophthalmic solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OralCream: Coding.FromStrict({
    code: "421873001",
    display: "Oral cream",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Oil: Coding.FromStrict({
    code: "421890007",
    display: "Oil",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MultilayerTablet: Coding.FromStrict({
    code: "421932003",
    display: "Multilayer tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MedicatedToothpaste: Coding.FromStrict({
    code: "421937009",
    display: "Medicated toothpaste",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_LyophilizedPowderForInjectableSuspension: Coding.FromStrict({
    code: "421943006",
    display: "Lyophilized powder for injectable suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CutaneousGel: Coding.FromStrict({
    code: "421949005",
    display: "Cutaneous gel",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_IntraocularSolution: Coding.FromStrict({
    code: "421987002",
    display: "Intraocular solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseCoatedPellets: Coding.FromStrict({
    code: "421999009",
    display: "Extended-release coated pellets",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MeteredDosePowderInhaler: Coding.FromStrict({
    code: "422054001",
    display: "Metered dose powder inhaler",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MeteredDoseInhaler: Coding.FromStrict({
    code: "422059006",
    display: "Metered dose inhaler",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OphthalmicSolution: Coding.FromStrict({
    code: "422060001",
    display: "Ophthalmic solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_EyeDropsSuspension: Coding.FromStrict({
    code: "422068008",
    display: "Eye drops suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalSuspension: Coding.FromStrict({
    code: "422080000",
    display: "Nasal suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForOphthalmicSuspension: Coding.FromStrict({
    code: "422085005",
    display: "Powder for ophthalmic suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_BreathActivatedPowderInhaler: Coding.FromStrict({
    code: "422151007",
    display: "Breath activated powder inhaler",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Tincture: Coding.FromStrict({
    code: "422186009",
    display: "Tincture",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_BreathActivatedInhaler: Coding.FromStrict({
    code: "422197009",
    display: "Breath activated inhaler",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DentalCone: Coding.FromStrict({
    code: "422199007",
    display: "Dental cone",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_TabletForCutaneousSolution: Coding.FromStrict({
    code: "422201009",
    display: "Tablet for cutaneous solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ColloidalSuspensionForInjection: Coding.FromStrict({
    code: "422202002",
    display: "Colloidal suspension for injection",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Spirit: Coding.FromStrict({
    code: "422259002",
    display: "Spirit",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PowderForInjectableExtendedReleaseSuspension: Coding.FromStrict({
    code: "422264003",
    display: "Powder for injectable extended release suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ModifiedReleasePessary: Coding.FromStrict({
    code: "422301006",
    display: "Modified-release pessary",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_NasalSolution: Coding.FromStrict({
    code: "422336005",
    display: "Nasal solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ExtendedReleaseSuspension: Coding.FromStrict({
    code: "422353003",
    display: "Extended-release suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_AerosolGenerator: Coding.FromStrict({
    code: "424179000",
    display: "Aerosol generator",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalSponge: Coding.FromStrict({
    code: "424552006",
    display: "Vaginal sponge",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_TopicalOintment: Coding.FromStrict({
    code: "425753008",
    display: "Topical ointment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_RectalSpray: Coding.FromStrict({
    code: "425965000",
    display: "Rectal spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Gum: Coding.FromStrict({
    code: "426210003",
    display: "Gum",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DropsDoseForm: Coding.FromStrict({
    code: "426684005",
    display: "Drops dose form",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_VaginalSpray: Coding.FromStrict({
    code: "426823003",
    display: "Vaginal spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_MeteredSpray: Coding.FromStrict({
    code: "426969004",
    display: "Metered spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_CoatedCapsule: Coding.FromStrict({
    code: "427129005",
    display: "Coated capsule",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_PressurizedSpray: Coding.FromStrict({
    code: "427564005",
    display: "Pressurized spray",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ModifiedReleaseDropsDoseForm: Coding.FromStrict({
    code: "427609008",
    display: "Modified release drops dose form",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Bar: Coding.FromStrict({
    code: "429885007",
    display: "Bar",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_BuccalFilm: Coding.FromStrict({
    code: "443424002",
    display: "Buccal film",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OrodispersibleFilm: Coding.FromStrict({
    code: "447050008",
    display: "Orodispersible film",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_OrodispersibleTablet: Coding.FromStrict({
    code: "447079001",
    display: "Orodispersible tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Pill: Coding.FromStrict({
    code: "46992007",
    display: "Pill",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Caplet: Coding.FromStrict({
    code: "48582000",
    display: "Caplet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DrugAerosol: Coding.FromStrict({
    code: "52262001",
    display: "Drug aerosol",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_Liniment: Coding.FromStrict({
    code: "63316001",
    display: "Liniment",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DrugPledget: Coding.FromStrict({
    code: "64241004",
    display: "Drug pledget",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_ChewableTablet: Coding.FromStrict({
    code: "66076007",
    display: "Chewable tablet",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DrugSolution: Coding.FromStrict({
    code: "77899000",
    display: "Drug solution",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DrugSuspension: Coding.FromStrict({
    code: "7946007",
    display: "Drug suspension",
    system: "http://snomed.info/sct"
  }),
  MedicationFormCodesValueSet_DrugPowder: Coding.FromStrict({
    code: "85581007",
    display: "Drug powder",
    system: "http://snomed.info/sct"
  }),
};
