// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Enum: http://hl7.org/fhir/ValueSet/verificationresult-validation-status|4.0.1

/**
 * Status of the validation of the target against the primary source
 */
export enum VerificationresultValidationStatusValueSetEnum {
  /**
   * Code: failed
   */
  Failed = "failed",
  /**
   * Code: successful
   */
  Successful = "successful",
  /**
   * unknown: The validations status has not been determined yet
   */
  Unknown = "unknown",
}
