// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
  // Primitive Naming Style: None
  // Complex Type / Resource Naming Style: PascalCase
  // Interaction Naming Style: None
  // Extension Support: NonPrimitive
// Minimum TypeScript Version: 3.7
import * as fhirModels from '../models'
/**
 * The Library resource is a general-purpose container for knowledge asset definitions. It can be used to describe and expose existing knowledge assets such as logic libraries and information model descriptions, as well as to describe a collection of knowledge assets.
 */
export class Library extends fhirModels.DomainResource {
  /**
   * Resource Type Name
   */
  readonly resourceType: string = "Library";
  /**
   * The 'date' element may be more recent than the approval date because of minor changes or editorial corrections.
   */
  approvalDate?: string;
  _approvalDate?: fhirModels.Element;
  /**
   * An individiual or organization primarily involved in the creation and maintenance of the content.
   */
  author?: fhirModels.ContactDetail[];
  /**
   * May be a web site, an email address, a telephone number, etc.
   */
  contact?: fhirModels.ContactDetail[];
  /**
   * The content of the library as an Attachment. The content may be a reference to a url, or may be directly embedded as a base-64 string. Either way, the contentType of the attachment determines how to interpret the content.
   */
  content?: fhirModels.Attachment[];
  /**
   * A copyright statement relating to the library and/or its contents. Copyright statements are generally legal restrictions on the use and publishing of the library.
   */
  copyright?: string;
  _copyright?: fhirModels.Element;
  /**
   * Describes a set of data that must be provided in order to be able to successfully perform the computations defined by the library.
   */
  dataRequirement?: fhirModels.DataRequirement[];
  /**
   * Note that this is not the same as the resource last-modified-date, since the resource may be a secondary representation of the library. Additional specific dates may be added as extensions or be found by consulting Provenances associated with past versions of the resource.
   */
  date?: string;
  _date?: fhirModels.Element;
  /**
   * This description can be used to capture details such as why the library was built, comments about misuse, instructions for clinical use and interpretation, literature references, examples from the paper world, etc. It is not a rendering of the library as conveyed in the 'text' field of the resource itself. This item SHOULD be populated unless the information is available from context (e.g. the language of the library is presumed to be the predominant language in the place the library was created).
   */
  description?: string;
  _description?: fhirModels.Element;
  /**
   * An individual or organization primarily responsible for internal coherence of the content.
   */
  editor?: fhirModels.ContactDetail[];
  /**
   * The effective period for a library  determines when the content is applicable for usage and is independent of publication and review dates. For example, a measure intended to be used for the year 2016 might be published in 2015.
   */
  effectivePeriod?: fhirModels.Period;
  /**
   * An individual or organization responsible for officially endorsing the content for use in some setting.
   */
  endorser?: fhirModels.ContactDetail[];
  /**
   * Allows filtering of librarys that are appropriate for use versus not.
   */
  experimental?: boolean;
  _experimental?: fhirModels.Element;
  /**
   * Typically, this is used for identifiers that can go in an HL7 V3 II (instance identifier) data type, and can then identify this library outside of FHIR, where it is not possible to use the logical URI.
   */
  identifier?: fhirModels.Identifier[];
  /**
   * It may be possible for the library to be used in jurisdictions other than those for which it was originally designed or intended.
   */
  jurisdiction?: fhirModels.CodeableConcept[];
  /**
   * If specified, this date follows the original approval date.
   */
  lastReviewDate?: string;
  _lastReviewDate?: fhirModels.Element;
  /**
   * The name is not expected to be globally unique. The name should be a simple alphanumeric type name to ensure that it is machine-processing friendly.
   */
  name?: string;
  _name?: fhirModels.Element;
  /**
   * The parameter element defines parameters used by the library.
   */
  parameter?: fhirModels.ParameterDefinition[];
  /**
   * Usually an organization but may be an individual. The publisher (or steward) of the library is the organization or individual primarily responsible for the maintenance and upkeep of the library. This is not necessarily the same individual or organization that developed and initially authored the content. The publisher is the primary point of contact for questions or issues with the library. This item SHOULD be populated unless the information is available from context.
   */
  publisher?: string;
  _publisher?: fhirModels.Element;
  /**
   * This element does not describe the usage of the library. Instead, it provides traceability of ''why'' the resource is either needed or ''why'' it is defined as it is.  This may be used to point to source materials or specifications that drove the structure of this library.
   */
  purpose?: string;
  _purpose?: fhirModels.Element;
  /**
   * Each related artifact is either an attachment, or a reference to another resource, but not both.
   */
  relatedArtifact?: fhirModels.RelatedArtifact[];
  /**
   * An individual or organization primarily responsible for review of some aspect of the content.
   */
  reviewer?: fhirModels.ContactDetail[];
  /**
   * Allows filtering of libraries that are appropriate for use vs. not.
   */
  status: LibraryStatusEnum;
  _status?: fhirModels.Element;
  /**
   * A code or group definition that describes the intended subject of the contents of the library.
   */
  subjectCodeableConcept?: fhirModels.CodeableConcept;
  /**
   * A code or group definition that describes the intended subject of the contents of the library.
   */
  subjectReference?: fhirModels.Reference;
  /**
   * An explanatory or alternate title for the library giving additional information about its content.
   */
  subtitle?: string;
  _subtitle?: fhirModels.Element;
  /**
   * This name does not need to be machine-processing friendly and may contain punctuation, white-space, etc.
   */
  title?: string;
  _title?: fhirModels.Element;
  /**
   * Descriptive topics related to the content of the library. Topics provide a high-level categorization of the library that can be useful for filtering and searching.
   */
  topic?: fhirModels.CodeableConcept[];
  /**
   * Identifies the type of library such as a Logic Library, Model Definition, Asset Collection, or Module Definition.
   */
  type: fhirModels.CodeableConcept;
  /**
   * Can be a urn:uuid: or a urn:oid: but real http: addresses are preferred.  Multiple instances may share the same URL if they have a distinct version.
   * The determination of when to create a new version of a resource (same url, new version) vs. defining a new artifact is up to the author.  Considerations for making this decision are found in [Technical and Business Versions](resource.html#versions). 
   * In some cases, the resource can no longer be found at the stated url, but the url itself cannot change. Implementations can use the [meta.source](resource.html#meta) element to indicate where the current master source of the resource can be found.
   */
  url?: string;
  _url?: fhirModels.Element;
  /**
   * A detailed description of how the library is used from a clinical perspective.
   */
  usage?: string;
  _usage?: fhirModels.Element;
  /**
   * When multiple useContexts are specified, there is no expectation that all or any of the contexts apply.
   */
  useContext?: fhirModels.UsageContext[];
  /**
   * There may be different library instances that have the same identifier but different versions.  The version can be appended to the url in a reference to allow a reference to a particular business version of the library with the format [url]|[version].
   */
  version?: string;
  _version?: fhirModels.Element;
  /**
   * Default constructor
   */
  constructor(source: Library) {
    super(source);
    if ((source['resourceType'] !== "Library") || (source['resourceType'] !== undefined)) { throw 'Invalid resourceType for a Library'; }
    if (source["approvalDate"] !== undefined) { this.approvalDate = source.approvalDate; }
    if (source["_approvalDate"] !== undefined) { this._approvalDate = source._approvalDate; }
    if (source["author"] !== undefined) { this.author = source.author; }
    if (source["contact"] !== undefined) { this.contact = source.contact; }
    if (source["content"] !== undefined) { this.content = source.content; }
    if (source["copyright"] !== undefined) { this.copyright = source.copyright; }
    if (source["_copyright"] !== undefined) { this._copyright = source._copyright; }
    if (source["dataRequirement"] !== undefined) { this.dataRequirement = source.dataRequirement; }
    if (source["date"] !== undefined) { this.date = source.date; }
    if (source["_date"] !== undefined) { this._date = source._date; }
    if (source["description"] !== undefined) { this.description = source.description; }
    if (source["_description"] !== undefined) { this._description = source._description; }
    if (source["editor"] !== undefined) { this.editor = source.editor; }
    if (source["effectivePeriod"] !== undefined) { this.effectivePeriod = source.effectivePeriod; }
    if (source["endorser"] !== undefined) { this.endorser = source.endorser; }
    if (source["experimental"] !== undefined) { this.experimental = source.experimental; }
    if (source["_experimental"] !== undefined) { this._experimental = source._experimental; }
    if (source["identifier"] !== undefined) { this.identifier = source.identifier; }
    if (source["jurisdiction"] !== undefined) { this.jurisdiction = source.jurisdiction; }
    if (source["lastReviewDate"] !== undefined) { this.lastReviewDate = source.lastReviewDate; }
    if (source["_lastReviewDate"] !== undefined) { this._lastReviewDate = source._lastReviewDate; }
    if (source["name"] !== undefined) { this.name = source.name; }
    if (source["_name"] !== undefined) { this._name = source._name; }
    if (source["parameter"] !== undefined) { this.parameter = source.parameter; }
    if (source["publisher"] !== undefined) { this.publisher = source.publisher; }
    if (source["_publisher"] !== undefined) { this._publisher = source._publisher; }
    if (source["purpose"] !== undefined) { this.purpose = source.purpose; }
    if (source["_purpose"] !== undefined) { this._purpose = source._purpose; }
    if (source["relatedArtifact"] !== undefined) { this.relatedArtifact = source.relatedArtifact; }
    if (source["reviewer"] !== undefined) { this.reviewer = source.reviewer; }
    if (source["status"] === undefined) { throw 'Missing required element status';}
    this.status = source.status;
    if (source["_status"] !== undefined) { this._status = source._status; }
    if (source["subjectCodeableConcept"] !== undefined) { this.subjectCodeableConcept = source.subjectCodeableConcept; }
    if (source["subjectReference"] !== undefined) { this.subjectReference = source.subjectReference; }
    if (source["subtitle"] !== undefined) { this.subtitle = source.subtitle; }
    if (source["_subtitle"] !== undefined) { this._subtitle = source._subtitle; }
    if (source["title"] !== undefined) { this.title = source.title; }
    if (source["_title"] !== undefined) { this._title = source._title; }
    if (source["topic"] !== undefined) { this.topic = source.topic; }
    if (source["type"] === undefined) { throw 'Missing required element type';}
    this.type = source.type;
    if (source["url"] !== undefined) { this.url = source.url; }
    if (source["_url"] !== undefined) { this._url = source._url; }
    if (source["usage"] !== undefined) { this.usage = source.usage; }
    if (source["_usage"] !== undefined) { this._usage = source._usage; }
    if (source["useContext"] !== undefined) { this.useContext = source.useContext; }
    if (source["version"] !== undefined) { this.version = source.version; }
    if (source["_version"] !== undefined) { this._version = source._version; }
  }
}
/**
 * Code Values for the Library.status field
 */
export enum LibraryStatusEnum {
  DRAFT = "draft",
  ACTIVE = "active",
  RETIRED = "retired",
  UNKNOWN = "unknown",
}
