// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
  // Primitive Naming Style: None
  // Complex Type / Resource Naming Style: PascalCase
  // Interaction Naming Style: None
  // Extension Support: NonPrimitive
// Minimum TypeScript Version: 3.7
import * as fhirModels from '../models'
/**
 * Indicates who or what performed the event.
 */
export class MedicationDispensePerformer extends fhirModels.BackboneElement {
  /**
   * The device, practitioner, etc. who performed the action.  It should be assumed that the actor is the dispenser of the medication.
   */
  actor: fhirModels.Reference;
  /**
   * Distinguishes the type of performer in the dispense.  For example, date enterer, packager, final checker.
   */
  function?: fhirModels.CodeableConcept;
  /**
   * Default constructor
   */
  constructor(source: MedicationDispensePerformer) {
    super(source);
    if (source["actor"] === undefined) { throw 'Missing required element actor';}
    this.actor = source.actor;
    if (source["function"] !== undefined) { this.function = source.function; }
  }
}
/**
 * Indicates whether or not substitution was made as part of the dispense.  In some cases, substitution will be expected but does not happen, in other cases substitution is not expected but does happen.  This block explains what substitution did or did not happen and why.  If nothing is specified, substitution was not done.
 */
export class MedicationDispenseSubstitution extends fhirModels.BackboneElement {
  /**
   * Indicates the reason for the substitution (or lack of substitution) from what was prescribed.
   */
  reason?: fhirModels.CodeableConcept[];
  /**
   * The person or organization that has primary responsibility for the substitution.
   */
  responsibleParty?: fhirModels.Reference[];
  /**
   * A code signifying whether a different drug was dispensed from what was prescribed.
   */
  type?: fhirModels.CodeableConcept;
  /**
   * True if the dispenser dispensed a different drug or product from what was prescribed.
   */
  wasSubstituted: boolean;
  _wasSubstituted?: fhirModels.Element;
  /**
   * Default constructor
   */
  constructor(source: MedicationDispenseSubstitution) {
    super(source);
    if (source["reason"] !== undefined) { this.reason = source.reason; }
    if (source["responsibleParty"] !== undefined) { this.responsibleParty = source.responsibleParty; }
    if (source["type"] !== undefined) { this.type = source.type; }
    if (source["wasSubstituted"] === undefined) { throw 'Missing required element wasSubstituted';}
    this.wasSubstituted = source.wasSubstituted;
    if (source["_wasSubstituted"] !== undefined) { this._wasSubstituted = source._wasSubstituted; }
  }
}
/**
 * Indicates that a medication product is to be or has been dispensed for a named person/patient.  This includes a description of the medication product (supply) provided and the instructions for administering the medication.  The medication dispense is the result of a pharmacy system responding to a medication order.
 */
export class MedicationDispense extends fhirModels.DomainResource {
  /**
   * Resource Type Name
   */
  readonly resourceType: string = "MedicationDispense";
  /**
   * Maps to basedOn in Event logical model.
   */
  authorizingPrescription?: fhirModels.Reference[];
  /**
   * The category can be used to include where the medication is expected to be consumed or other types of dispenses.  Invariants can be used to bind to different value sets when profiling to bind.
   */
  category?: fhirModels.CodeableConcept;
  /**
   * The encounter or episode of care that establishes the context for this event.
   */
  context?: fhirModels.Reference;
  /**
   * The amount of medication expressed as a timing amount.
   */
  daysSupply?: fhirModels.Quantity;
  /**
   * Identification of the facility/location where the medication was shipped to, as part of the dispense event.
   */
  destination?: fhirModels.Reference;
  /**
   * This element can include a detected issue that has been identified either by a decision support system or by a clinician and may include information on the steps that were taken to address the issue.
   */
  detectedIssue?: fhirModels.Reference[];
  /**
   * When the dose or rate is intended to change over the entire administration period (e.g. Tapering dose prescriptions), multiple instances of dosage instructions will need to be supplied to convey the different doses/rates.
   * The pharmacist reviews the medication order prior to dispense and updates the dosageInstruction based on the actual product being dispensed.
   */
  dosageInstruction?: fhirModels.Dosage[];
  /**
   * This might not include provenances for all versions of the request – only those deemed “relevant” or important. This SHALL NOT include the Provenance associated with this current version of the resource. (If that provenance is deemed to be a “relevant” change, it will need to be added as part of a later update. Until then, it can be queried directly as the Provenance that points to this version using _revinclude All Provenances should have some historical version of this Request as their subject.).
   */
  eventHistory?: fhirModels.Reference[];
  /**
   * This is a business identifier, not a resource identifier.
   */
  identifier?: fhirModels.Identifier[];
  /**
   * The principal physical location where the dispense was performed.
   */
  location?: fhirModels.Reference;
  /**
   * If only a code is specified, then it needs to be a code for a specific product. If more information is required, then the use of the medication resource is recommended.  For example, if you require form or lot number, then you must reference the Medication resource.
   */
  medicationCodeableConcept?: fhirModels.CodeableConcept;
  /**
   * If only a code is specified, then it needs to be a code for a specific product. If more information is required, then the use of the medication resource is recommended.  For example, if you require form or lot number, then you must reference the Medication resource.
   */
  medicationReference?: fhirModels.Reference;
  /**
   * Extra information about the dispense that could not be conveyed in the other attributes.
   */
  note?: fhirModels.Annotation[];
  /**
   * The procedure that trigger the dispense.
   */
  partOf?: fhirModels.Reference[];
  /**
   * Indicates who or what performed the event.
   */
  performer?: fhirModels.MedicationDispensePerformer[];
  /**
   * The amount of medication that has been dispensed. Includes unit of measure.
   */
  quantity?: fhirModels.Quantity;
  /**
   * Identifies the person who picked up the medication.  This will usually be a patient or their caregiver, but some cases exist where it can be a healthcare professional.
   */
  receiver?: fhirModels.Reference[];
  /**
   * This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.
   */
  status: MedicationDispenseStatusEnum;
  _status?: fhirModels.Element;
  /**
   * Indicates the reason why a dispense was not performed.
   */
  statusReasonCodeableConcept?: fhirModels.CodeableConcept;
  /**
   * Indicates the reason why a dispense was not performed.
   */
  statusReasonReference?: fhirModels.Reference;
  /**
   * SubstanceAdministration-&gt;subject-&gt;Patient.
   */
  subject?: fhirModels.Reference;
  /**
   * Indicates whether or not substitution was made as part of the dispense.  In some cases, substitution will be expected but does not happen, in other cases substitution is not expected but does happen.  This block explains what substitution did or did not happen and why.  If nothing is specified, substitution was not done.
   */
  substitution?: fhirModels.MedicationDispenseSubstitution;
  /**
   * Additional information that supports the medication being dispensed.
   */
  supportingInformation?: fhirModels.Reference[];
  /**
   * Indicates the type of dispensing event that is performed. For example, Trial Fill, Completion of Trial, Partial Fill, Emergency Fill, Samples, etc.
   */
  type?: fhirModels.CodeableConcept;
  /**
   * The time the dispensed product was provided to the patient or their representative.
   */
  whenHandedOver?: string;
  _whenHandedOver?: fhirModels.Element;
  /**
   * The time when the dispensed product was packaged and reviewed.
   */
  whenPrepared?: string;
  _whenPrepared?: fhirModels.Element;
  /**
   * Default constructor
   */
  constructor(source: MedicationDispense) {
    super(source);
    if ((source['resourceType'] !== "MedicationDispense") || (source['resourceType'] !== undefined)) { throw 'Invalid resourceType for a MedicationDispense'; }
    if (source["authorizingPrescription"] !== undefined) { this.authorizingPrescription = source.authorizingPrescription; }
    if (source["category"] !== undefined) { this.category = source.category; }
    if (source["context"] !== undefined) { this.context = source.context; }
    if (source["daysSupply"] !== undefined) { this.daysSupply = source.daysSupply; }
    if (source["destination"] !== undefined) { this.destination = source.destination; }
    if (source["detectedIssue"] !== undefined) { this.detectedIssue = source.detectedIssue; }
    if (source["dosageInstruction"] !== undefined) { this.dosageInstruction = source.dosageInstruction; }
    if (source["eventHistory"] !== undefined) { this.eventHistory = source.eventHistory; }
    if (source["identifier"] !== undefined) { this.identifier = source.identifier; }
    if (source["location"] !== undefined) { this.location = source.location; }
    if (source["medicationCodeableConcept"] !== undefined) { this.medicationCodeableConcept = source.medicationCodeableConcept; }
    if (source["medicationReference"] !== undefined) { this.medicationReference = source.medicationReference; }
    if (source["note"] !== undefined) { this.note = source.note; }
    if (source["partOf"] !== undefined) { this.partOf = source.partOf; }
    if (source["performer"] !== undefined) { this.performer = source.performer; }
    if (source["quantity"] !== undefined) { this.quantity = source.quantity; }
    if (source["receiver"] !== undefined) { this.receiver = source.receiver; }
    if (source["status"] === undefined) { throw 'Missing required element status';}
    this.status = source.status;
    if (source["_status"] !== undefined) { this._status = source._status; }
    if (source["statusReasonCodeableConcept"] !== undefined) { this.statusReasonCodeableConcept = source.statusReasonCodeableConcept; }
    if (source["statusReasonReference"] !== undefined) { this.statusReasonReference = source.statusReasonReference; }
    if (source["subject"] !== undefined) { this.subject = source.subject; }
    if (source["substitution"] !== undefined) { this.substitution = source.substitution; }
    if (source["supportingInformation"] !== undefined) { this.supportingInformation = source.supportingInformation; }
    if (source["type"] !== undefined) { this.type = source.type; }
    if (source["whenHandedOver"] !== undefined) { this.whenHandedOver = source.whenHandedOver; }
    if (source["_whenHandedOver"] !== undefined) { this._whenHandedOver = source._whenHandedOver; }
    if (source["whenPrepared"] !== undefined) { this.whenPrepared = source.whenPrepared; }
    if (source["_whenPrepared"] !== undefined) { this._whenPrepared = source._whenPrepared; }
  }
}
/**
 * Code Values for the MedicationDispense.status field
 */
export enum MedicationDispenseStatusEnum {
  PREPARATION = "preparation",
  IN_PROGRESS = "in-progress",
  CANCELLED = "cancelled",
  ON_HOLD = "on-hold",
  COMPLETED = "completed",
  ENTERED_IN_ERROR = "entered-in-error",
  STOPPED = "stopped",
  DECLINED = "declined",
  UNKNOWN = "unknown",
}
