// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
  // Primitive Naming Style: None
  // Complex Type / Resource Naming Style: PascalCase
  // Interaction Naming Style: None
  // Extension Support: NonPrimitive
// Minimum TypeScript Version: 3.7
import * as fhirModels from '../models'
/**
 * Many complex materials are fractions of parts of plants, animals, or minerals. Fraction elements are often necessary to define both Substances and Specified Group 1 Substances. For substances derived from Plants, fraction information will be captured at the Substance information level ( . Oils, Juices and Exudates). Additional information for Extracts, such as extraction solvent composition, will be captured at the Specified Substance Group 1 information level. For plasma-derived products fraction information will be captured at the Substance and the Specified Substance Group 1 levels.
 */
export class SubstanceSourceMaterialFractionDescription extends fhirModels.BackboneElement {
  /**
   * This element is capturing information about the fraction of a plant part, or human plasma for fractionation.
   */
  fraction?: string;
  _fraction?: fhirModels.Element;
  /**
   * The specific type of the material constituting the component. For Herbal preparations the particulars of the extracts (liquid/dry) is described in Specified Substance Group 1.
   */
  materialType?: fhirModels.CodeableConcept;
  /**
   * Default constructor
   */
  constructor(source: SubstanceSourceMaterialFractionDescription) {
    super(source);
    if (source["fraction"] !== undefined) { this.fraction = source.fraction; }
    if (source["_fraction"] !== undefined) { this._fraction = source._fraction; }
    if (source["materialType"] !== undefined) { this.materialType = source.materialType; }
  }
}
/**
 * 4.9.13.6.1 Author type (Conditional).
 */
export class SubstanceSourceMaterialOrganismAuthor extends fhirModels.BackboneElement {
  /**
   * The author of an organism species shall be specified. The author year of an organism shall also be specified when applicable; refers to the year in which the first author(s) published the infraspecific plant/animal name (of any rank).
   */
  authorDescription?: string;
  _authorDescription?: fhirModels.Element;
  /**
   * The type of author of an organism species shall be specified. The parenthetical author of an organism species refers to the first author who published the plant/animal name (of any rank). The primary author of an organism species refers to the first author(s), who validly published the plant/animal name.
   */
  authorType?: fhirModels.CodeableConcept;
  /**
   * Default constructor
   */
  constructor(source: SubstanceSourceMaterialOrganismAuthor) {
    super(source);
    if (source["authorDescription"] !== undefined) { this.authorDescription = source.authorDescription; }
    if (source["_authorDescription"] !== undefined) { this._authorDescription = source._authorDescription; }
    if (source["authorType"] !== undefined) { this.authorType = source.authorType; }
  }
}
/**
 * 4.9.13.8.1 Hybrid species maternal organism ID (Optional).
 */
export class SubstanceSourceMaterialOrganismHybrid extends fhirModels.BackboneElement {
  /**
   * The hybrid type of an organism shall be specified.
   */
  hybridType?: fhirModels.CodeableConcept;
  /**
   * The identifier of the maternal species constituting the hybrid organism shall be specified based on a controlled vocabulary. For plants, the parents aren’t always known, and it is unlikely that it will be known which is maternal and which is paternal.
   */
  maternalOrganismId?: string;
  _maternalOrganismId?: fhirModels.Element;
  /**
   * The name of the maternal species constituting the hybrid organism shall be specified. For plants, the parents aren’t always known, and it is unlikely that it will be known which is maternal and which is paternal.
   */
  maternalOrganismName?: string;
  _maternalOrganismName?: fhirModels.Element;
  /**
   * The identifier of the paternal species constituting the hybrid organism shall be specified based on a controlled vocabulary.
   */
  paternalOrganismId?: string;
  _paternalOrganismId?: fhirModels.Element;
  /**
   * The name of the paternal species constituting the hybrid organism shall be specified.
   */
  paternalOrganismName?: string;
  _paternalOrganismName?: fhirModels.Element;
  /**
   * Default constructor
   */
  constructor(source: SubstanceSourceMaterialOrganismHybrid) {
    super(source);
    if (source["hybridType"] !== undefined) { this.hybridType = source.hybridType; }
    if (source["maternalOrganismId"] !== undefined) { this.maternalOrganismId = source.maternalOrganismId; }
    if (source["_maternalOrganismId"] !== undefined) { this._maternalOrganismId = source._maternalOrganismId; }
    if (source["maternalOrganismName"] !== undefined) { this.maternalOrganismName = source.maternalOrganismName; }
    if (source["_maternalOrganismName"] !== undefined) { this._maternalOrganismName = source._maternalOrganismName; }
    if (source["paternalOrganismId"] !== undefined) { this.paternalOrganismId = source.paternalOrganismId; }
    if (source["_paternalOrganismId"] !== undefined) { this._paternalOrganismId = source._paternalOrganismId; }
    if (source["paternalOrganismName"] !== undefined) { this.paternalOrganismName = source.paternalOrganismName; }
    if (source["_paternalOrganismName"] !== undefined) { this._paternalOrganismName = source._paternalOrganismName; }
  }
}
/**
 * 4.9.13.7.1 Kingdom (Conditional).
 */
export class SubstanceSourceMaterialOrganismOrganismGeneral extends fhirModels.BackboneElement {
  /**
   * The class of an organism shall be specified.
   */
  class?: fhirModels.CodeableConcept;
  /**
   * The kingdom of an organism shall be specified.
   */
  kingdom?: fhirModels.CodeableConcept;
  /**
   * The order of an organism shall be specified,.
   */
  order?: fhirModels.CodeableConcept;
  /**
   * The phylum of an organism shall be specified.
   */
  phylum?: fhirModels.CodeableConcept;
  /**
   * Default constructor
   */
  constructor(source: SubstanceSourceMaterialOrganismOrganismGeneral) {
    super(source);
    if (source["class"] !== undefined) { this.class = source.class; }
    if (source["kingdom"] !== undefined) { this.kingdom = source.kingdom; }
    if (source["order"] !== undefined) { this.order = source.order; }
    if (source["phylum"] !== undefined) { this.phylum = source.phylum; }
  }
}
/**
 * This subclause describes the organism which the substance is derived from. For vaccines, the parent organism shall be specified based on these subclause elements. As an example, full taxonomy will be described for the Substance Name: ., Leaf.
 */
export class SubstanceSourceMaterialOrganism extends fhirModels.BackboneElement {
  /**
   * 4.9.13.6.1 Author type (Conditional).
   */
  author?: fhirModels.SubstanceSourceMaterialOrganismAuthor[];
  /**
   * The family of an organism shall be specified.
   */
  family?: fhirModels.CodeableConcept;
  /**
   * The genus of an organism shall be specified; refers to the Latin epithet of the genus element of the plant/animal scientific name; it is present in names for genera, species and infraspecies.
   */
  genus?: fhirModels.CodeableConcept;
  /**
   * 4.9.13.8.1 Hybrid species maternal organism ID (Optional).
   */
  hybrid?: fhirModels.SubstanceSourceMaterialOrganismHybrid;
  /**
   * The intraspecific description of an organism shall be specified based on a controlled vocabulary. For Influenza Vaccine, the intraspecific description shall contain the syntax of the antigen in line with the WHO convention.
   */
  intraspecificDescription?: string;
  _intraspecificDescription?: fhirModels.Element;
  /**
   * The Intraspecific type of an organism shall be specified.
   */
  intraspecificType?: fhirModels.CodeableConcept;
  /**
   * 4.9.13.7.1 Kingdom (Conditional).
   */
  organismGeneral?: fhirModels.SubstanceSourceMaterialOrganismOrganismGeneral;
  /**
   * The species of an organism shall be specified; refers to the Latin epithet of the species of the plant/animal; it is present in names for species and infraspecies.
   */
  species?: fhirModels.CodeableConcept;
  /**
   * Default constructor
   */
  constructor(source: SubstanceSourceMaterialOrganism) {
    super(source);
    if (source["author"] !== undefined) { this.author = source.author; }
    if (source["family"] !== undefined) { this.family = source.family; }
    if (source["genus"] !== undefined) { this.genus = source.genus; }
    if (source["hybrid"] !== undefined) { this.hybrid = source.hybrid; }
    if (source["intraspecificDescription"] !== undefined) { this.intraspecificDescription = source.intraspecificDescription; }
    if (source["_intraspecificDescription"] !== undefined) { this._intraspecificDescription = source._intraspecificDescription; }
    if (source["intraspecificType"] !== undefined) { this.intraspecificType = source.intraspecificType; }
    if (source["organismGeneral"] !== undefined) { this.organismGeneral = source.organismGeneral; }
    if (source["species"] !== undefined) { this.species = source.species; }
  }
}
/**
 * To do.
 */
export class SubstanceSourceMaterialPartDescription extends fhirModels.BackboneElement {
  /**
   * Entity of anatomical origin of source material within an organism.
   */
  part?: fhirModels.CodeableConcept;
  /**
   * The detailed anatomic location when the part can be extracted from different anatomical locations of the organism. Multiple alternative locations may apply.
   */
  partLocation?: fhirModels.CodeableConcept;
  /**
   * Default constructor
   */
  constructor(source: SubstanceSourceMaterialPartDescription) {
    super(source);
    if (source["part"] !== undefined) { this.part = source.part; }
    if (source["partLocation"] !== undefined) { this.partLocation = source.partLocation; }
  }
}
/**
 * Source material shall capture information on the taxonomic and anatomical origins as well as the fraction of a material that can result in or can be modified to form a substance. This set of data elements shall be used to define polymer substances isolated from biological matrices. Taxonomic and anatomical origins shall be described using a controlled vocabulary as required. This information is captured for naturally derived polymers ( . starch) and structurally diverse substances. For Organisms belonging to the Kingdom Plantae the Substance level defines the fresh material of a single species or infraspecies, the Herbal Drug and the Herbal preparation. For Herbal preparations, the fraction information will be captured at the Substance information level and additional information for herbal extracts will be captured at the Specified Substance Group 1 information level. See for further explanation the Substance Class: Structurally Diverse and the herbal annex.
 */
export class SubstanceSourceMaterial extends fhirModels.DomainResource {
  /**
   * Resource Type Name
   */
  readonly resourceType: string = "SubstanceSourceMaterial";
  /**
   * The country where the plant material is harvested or the countries where the plasma is sourced from as laid down in accordance with the Plasma Master File. For “Plasma-derived substances” the attribute country of origin provides information about the countries used for the manufacturing of the Cryopoor plama or Crioprecipitate.
   */
  countryOfOrigin?: fhirModels.CodeableConcept[];
  /**
   * Stage of life for animals, plants, insects and microorganisms. This information shall be provided only when the substance is significantly different in these stages (e.g. foetal bovine serum).
   */
  developmentStage?: fhirModels.CodeableConcept;
  /**
   * Many complex materials are fractions of parts of plants, animals, or minerals. Fraction elements are often necessary to define both Substances and Specified Group 1 Substances. For substances derived from Plants, fraction information will be captured at the Substance information level ( . Oils, Juices and Exudates). Additional information for Extracts, such as extraction solvent composition, will be captured at the Specified Substance Group 1 information level. For plasma-derived products fraction information will be captured at the Substance and the Specified Substance Group 1 levels.
   */
  fractionDescription?: fhirModels.SubstanceSourceMaterialFractionDescription[];
  /**
   * The place/region where the plant is harvested or the places/regions where the animal source material has its habitat.
   */
  geographicalLocation?: string[];
  _geographicalLocation?: fhirModels.Element[];
  /**
   * This subclause describes the organism which the substance is derived from. For vaccines, the parent organism shall be specified based on these subclause elements. As an example, full taxonomy will be described for the Substance Name: ., Leaf.
   */
  organism?: fhirModels.SubstanceSourceMaterialOrganism;
  /**
   * The unique identifier associated with the source material parent organism shall be specified.
   */
  organismId?: fhirModels.Identifier;
  /**
   * The organism accepted Scientific name shall be provided based on the organism taxonomy.
   */
  organismName?: string;
  _organismName?: fhirModels.Element;
  /**
   * The parent of the herbal drug Ginkgo biloba, Leaf is the substance ID of the substance (fresh) of Ginkgo biloba L. or Ginkgo biloba L. (Whole plant).
   */
  parentSubstanceId?: fhirModels.Identifier[];
  /**
   * The parent substance of the Herbal Drug, or Herbal preparation.
   */
  parentSubstanceName?: string[];
  _parentSubstanceName?: fhirModels.Element[];
  /**
   * To do.
   */
  partDescription?: fhirModels.SubstanceSourceMaterialPartDescription[];
  /**
   * General high level classification of the source material specific to the origin of the material.
   */
  sourceMaterialClass?: fhirModels.CodeableConcept;
  /**
   * The state of the source material when extracted.
   */
  sourceMaterialState?: fhirModels.CodeableConcept;
  /**
   * The type of the source material shall be specified based on a controlled vocabulary. For vaccines, this subclause refers to the class of infectious agent.
   */
  sourceMaterialType?: fhirModels.CodeableConcept;
  /**
   * Default constructor
   */
  constructor(source: SubstanceSourceMaterial) {
    super(source);
    if ((source['resourceType'] !== "SubstanceSourceMaterial") || (source['resourceType'] !== undefined)) { throw 'Invalid resourceType for a SubstanceSourceMaterial'; }
    if (source["countryOfOrigin"] !== undefined) { this.countryOfOrigin = source.countryOfOrigin; }
    if (source["developmentStage"] !== undefined) { this.developmentStage = source.developmentStage; }
    if (source["fractionDescription"] !== undefined) { this.fractionDescription = source.fractionDescription; }
    if (source["geographicalLocation"] !== undefined) { this.geographicalLocation = source.geographicalLocation; }
    if (source["_geographicalLocation"] !== undefined) { this._geographicalLocation = source._geographicalLocation; }
    if (source["organism"] !== undefined) { this.organism = source.organism; }
    if (source["organismId"] !== undefined) { this.organismId = source.organismId; }
    if (source["organismName"] !== undefined) { this.organismName = source.organismName; }
    if (source["_organismName"] !== undefined) { this._organismName = source._organismName; }
    if (source["parentSubstanceId"] !== undefined) { this.parentSubstanceId = source.parentSubstanceId; }
    if (source["parentSubstanceName"] !== undefined) { this.parentSubstanceName = source.parentSubstanceName; }
    if (source["_parentSubstanceName"] !== undefined) { this._parentSubstanceName = source._parentSubstanceName; }
    if (source["partDescription"] !== undefined) { this.partDescription = source.partDescription; }
    if (source["sourceMaterialClass"] !== undefined) { this.sourceMaterialClass = source.sourceMaterialClass; }
    if (source["sourceMaterialState"] !== undefined) { this.sourceMaterialState = source.sourceMaterialState; }
    if (source["sourceMaterialType"] !== undefined) { this.sourceMaterialType = source.sourceMaterialType; }
  }
}
